using System;
using System.Collections.Generic;

namespace KhimTools.QuantityTakeoff.Models
{
    public sealed class QsChangeEvent { public string ChangeEventId { get; set; } = Guid.NewGuid().ToString("N"); public string ChangeNumber { get; set; } = ""; public string Title { get; set; } = ""; public string ChangeType { get; set; } = "MODEL_REVISION"; public string SourceType { get; set; } = "MANUAL"; public string SourceReference { get; set; } = ""; public DateTime RaisedDate { get; set; } = DateTime.UtcNow; public string Status { get; set; } = "IDENTIFIED"; public string Priority { get; set; } = "MEDIUM"; public decimal PotentialCostImpact { get; set; } public int PotentialTimeImpactDays { get; set; } public string Currency { get; set; } = "VND"; public List<string> AffectedBoqCodes { get; set; } = new List<string>(); public List<string> AffectedTaskIds { get; set; } = new List<string>(); public List<string> AffectedElementUniqueIds { get; set; } = new List<string>(); }
    public sealed class QsChangeImpactAssessment { public string AssessmentId { get; set; } = Guid.NewGuid().ToString("N"); public string ChangeEventId { get; set; } = ""; public int Revision { get; set; } public DateTime AssessmentDate { get; set; } = DateTime.UtcNow; public decimal DirectCostImpact { get; set; } public decimal IndirectCostImpact { get; set; } public decimal TotalCostImpact { get; set; } public int TimeImpactDays { get; set; } public string Currency { get; set; } = "VND"; public string Status { get; set; } = "PRELIMINARY"; public string Assumptions { get; set; } = ""; }
    public sealed class QsChangeQuantityImpact { public string ChangeEventId { get; set; } = ""; public string MeasurementCode { get; set; } = ""; public string BoqCode { get; set; } = ""; public double BaselineQuantity { get; set; } public double CurrentQuantity { get; set; } public double QuantityDelta => CurrentQuantity - BaselineQuantity; public string Unit { get; set; } = ""; public List<string> RelatedUniqueIds { get; set; } = new List<string>(); }
    public sealed class QsChangeCostImpact { public string ChangeEventId { get; set; } = ""; public string BoqCode { get; set; } = ""; public double QuantityDelta { get; set; } public decimal Rate { get; set; } public decimal DirectCost { get; set; } public decimal IndirectCost { get; set; } public decimal TotalCost { get; set; } public string RateSource { get; set; } = "CONTRACT_RATE"; public string Currency { get; set; } = "VND"; }
    public sealed class QsChangeScheduleImpact { public string ChangeEventId { get; set; } = ""; public string TaskId { get; set; } = ""; public DateTime? BaselineFinish { get; set; } public DateTime? CurrentFinish { get; set; } public int DelayDays { get; set; } public string ImpactType { get; set; } = "OTHER"; public string Status { get; set; } = "POTENTIAL"; }
    public sealed class QsExtensionOfTime { public string EotId { get; set; } = Guid.NewGuid().ToString("N"); public string EotNumber { get; set; } = ""; public string ChangeEventId { get; set; } = ""; public int ClaimedDays { get; set; } public int AssessedDays { get; set; } public int ApprovedDays { get; set; } public string Status { get; set; } = "DRAFT"; public string Cause { get; set; } = ""; public DateTime? ApprovalDate { get; set; } }
    public sealed class QsClaim { public string ClaimId { get; set; } = Guid.NewGuid().ToString("N"); public string ClaimNumber { get; set; } = ""; public string ChangeEventId { get; set; } = ""; public string ClaimType { get; set; } = "VARIATION"; public decimal ClaimedAmount { get; set; } public decimal AssessedAmount { get; set; } public decimal ApprovedAmount { get; set; } public int ClaimedDays { get; set; } public int ApprovedDays { get; set; } public string Status { get; set; } = "DRAFT"; }
    public sealed class QsRfi { public string RfiId { get; set; } = Guid.NewGuid().ToString("N"); public string RfiNumber { get; set; } = ""; public string Title { get; set; } = ""; public DateTime RaisedDate { get; set; } = DateTime.UtcNow; public DateTime? RequiredResponseDate { get; set; } public DateTime? RespondedDate { get; set; } public string Question { get; set; } = ""; public string Response { get; set; } = ""; public string Status { get; set; } = "OPEN"; public string RelatedChangeEventId { get; set; } = ""; }
    public sealed class QsRisk { public string RiskId { get; set; } = Guid.NewGuid().ToString("N"); public string RiskNumber { get; set; } = ""; public string Title { get; set; } = ""; public int Probability { get; set; } public int Impact { get; set; } public int RiskScore => Probability * Impact; public string Owner { get; set; } = ""; public decimal CostExposure { get; set; } public int TimeExposureDays { get; set; } public string Status { get; set; } = "OPEN"; public string ResponseStrategy { get; set; } = "MITIGATE"; }
    public sealed class QsIssueRecord { public string IssueId { get; set; } = Guid.NewGuid().ToString("N"); public string IssueNumber { get; set; } = ""; public string Title { get; set; } = ""; public string Status { get; set; } = "OPEN"; public string RelatedRiskId { get; set; } = ""; public string RelatedChangeEventId { get; set; } = ""; public DateTime? DueDate { get; set; } }
}
