using System;
using System.Collections.Generic;

namespace KhimTools.QuantityTakeoff.Models
{
    public sealed class QsProcurementPackage { public string PackageId { get; set; } = Guid.NewGuid().ToString("N"); public string PackageCode { get; set; } = ""; public string Name { get; set; } = ""; public string ProcurementType { get; set; } = "MATERIAL"; public string WorkPackage { get; set; } = ""; public string WbsId { get; set; } = ""; public DateTime? RequiredOnSiteDate { get; set; } public DateTime? RFQPlannedDate { get; set; } public DateTime? AwardPlannedDate { get; set; } public DateTime? DeliveryPlannedDate { get; set; } public string Status { get; set; } = "DRAFT"; public string Currency { get; set; } = "VND"; public decimal BudgetAmount { get; set; } public List<string> BoqCodes { get; set; } = new List<string>(); }
    public sealed class QsMaterialRequirement { public string RequirementId { get; set; } = Guid.NewGuid().ToString("N"); public string PackageId { get; set; } = ""; public string MaterialCode { get; set; } = ""; public string Description { get; set; } = ""; public string Unit { get; set; } = ""; public double RequiredQuantity { get; set; } public double WastePercent { get; set; } public double OrderedQuantity { get; set; } public double DeliveredQuantity { get; set; } public double AcceptedQuantity { get; set; } public double RejectedQuantity { get; set; } public double RemainingQuantity => Math.Max(0, RequiredQuantity * (1 + WastePercent / 100) - AcceptedQuantity); public DateTime? RequiredDate { get; set; } public string BoqCode { get; set; } = ""; public string MeasurementCode { get; set; } = ""; public string SourceType { get; set; } = "MODEL_QUANTITY"; public List<string> SourceQuantityIds { get; set; } = new List<string>(); }
    public sealed class QsVendor { public string VendorId { get; set; } = Guid.NewGuid().ToString("N"); public string VendorCode { get; set; } = ""; public string Name { get; set; } = ""; public string VendorType { get; set; } = "SUPPLIER"; public string ContactPerson { get; set; } = ""; public string Email { get; set; } = ""; public string Currency { get; set; } = "VND"; public string Status { get; set; } = "ACTIVE"; }
    public sealed class QsRfq { public string RfqId { get; set; } = Guid.NewGuid().ToString("N"); public string RfqNumber { get; set; } = ""; public string PackageId { get; set; } = ""; public DateTime IssueDate { get; set; } public DateTime DueDate { get; set; } public string Currency { get; set; } = "VND"; public string Status { get; set; } = "DRAFT"; public List<string> VendorIds { get; set; } = new List<string>(); }
    public sealed class QsVendorQuotation { public string QuotationId { get; set; } = Guid.NewGuid().ToString("N"); public string RfqId { get; set; } = ""; public string VendorId { get; set; } = ""; public string QuotationNumber { get; set; } = ""; public decimal TotalQuotedAmount { get; set; } public decimal FinalQuotedAmount { get; set; } public int DeliveryDays { get; set; } public string Currency { get; set; } = "VND"; public string ComplianceStatus { get; set; } = "NOT_REVIEWED"; public bool IsAwarded { get; set; } public List<QsQuotationLine> Lines { get; set; } = new List<QsQuotationLine>(); }
    public sealed class QsQuotationLine { public string MaterialCode { get; set; } = ""; public string BoqCode { get; set; } = ""; public double Quantity { get; set; } public string Unit { get; set; } = ""; public decimal UnitRate { get; set; } public decimal Amount => (decimal)Quantity * UnitRate; }
    public sealed class QsPurchaseOrder { public string PoId { get; set; } = Guid.NewGuid().ToString("N"); public string PoNumber { get; set; } = ""; public string PackageId { get; set; } = ""; public string VendorId { get; set; } = ""; public DateTime IssueDate { get; set; } public string Currency { get; set; } = "VND"; public decimal OriginalAmount { get; set; } public decimal VariationAmount { get; set; } public decimal CurrentAmount => OriginalAmount + VariationAmount; public string Status { get; set; } = "DRAFT"; public List<QsPurchaseOrderLine> Lines { get; set; } = new List<QsPurchaseOrderLine>(); }
    public sealed class QsPurchaseOrderLine { public string PoLineId { get; set; } = Guid.NewGuid().ToString("N"); public string MaterialCode { get; set; } = ""; public string BoqCode { get; set; } = ""; public double OrderedQuantity { get; set; } public string Unit { get; set; } = ""; public decimal UnitRate { get; set; } public decimal Amount => (decimal)OrderedQuantity * UnitRate; }
    public sealed class QsDelivery { public string DeliveryId { get; set; } = Guid.NewGuid().ToString("N"); public string PoId { get; set; } = ""; public DateTime DeliveryDate { get; set; } public string Status { get; set; } = "EXPECTED"; public List<QsDeliveryLine> Lines { get; set; } = new List<QsDeliveryLine>(); }
    public sealed class QsDeliveryLine { public string PoLineId { get; set; } = ""; public double DeliveredQuantity { get; set; } public double AcceptedQuantity { get; set; } public double RejectedQuantity { get; set; } public string InspectionStatus { get; set; } = "NOT_REVIEWED"; }
}
