using System;
using System.Collections.Generic;

namespace KhimTools.QuantityTakeoff.Models
{
    public enum QsClassificationStatus { Classified, Unclassified, Ambiguous, Ignored }
    public sealed class QsBoqItem { public string BoqCode { get; set; } = ""; public string Description { get; set; } = ""; public string WorkPackage { get; set; } = ""; public string Discipline { get; set; } = ""; public string Unit { get; set; } = ""; public string ParentCode { get; set; } = ""; public int SortOrder { get; set; } public bool IsActive { get; set; } = true; }
    public sealed class QsBoqRule { public string Id { get; set; } = Guid.NewGuid().ToString("N"); public int Priority { get; set; } public string Category { get; set; } = ""; public string FamilyPattern { get; set; } = ""; public string TypePattern { get; set; } = ""; public string MaterialPattern { get; set; } = ""; public string MeasurementCode { get; set; } = ""; public string TargetBoqCode { get; set; } = ""; public bool Enabled { get; set; } = true; }
    public sealed class QsClassificationResult { public string BoqCode { get; set; } = ""; public QsClassificationStatus Status { get; set; } public string Message { get; set; } = ""; }
    public sealed class QsQuantitySnapshot { public string SchemaVersion { get; set; } = "KQS_Snapshot_v1"; public string SnapshotId { get; set; } = Guid.NewGuid().ToString("N"); public string Name { get; set; } = ""; public string ProjectTitle { get; set; } = ""; public string DocumentPath { get; set; } = ""; public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow; public string ScanScope { get; set; } = "ActiveView"; public List<QsSnapshotElement> Elements { get; set; } = new List<QsSnapshotElement>(); public List<QsSnapshotQuantity> Quantities { get; set; } = new List<QsSnapshotQuantity>(); }
    public sealed class QsSnapshotElement { public string UniqueId { get; set; } = ""; public int ElementIdAtSnapshot { get; set; } public string Category { get; set; } = ""; public string Family { get; set; } = ""; public string Type { get; set; } = ""; public string Level { get; set; } = ""; public string Fingerprint { get; set; } = ""; }
    public sealed class QsSnapshotQuantity { public string ElementUniqueId { get; set; } = ""; public string MeasurementCode { get; set; } = ""; public string BoqCode { get; set; } = ""; public double Quantity { get; set; } public string Unit { get; set; } = ""; public string Material { get; set; } = ""; public string Level { get; set; } = ""; }
    public sealed class QsCompareRow { public string Status { get; set; } = ""; public string ChangeReasons { get; set; } = ""; public string UniqueId { get; set; } = ""; public string Category { get; set; } = ""; public string OldType { get; set; } = ""; public string NewType { get; set; } = ""; public string Measurement { get; set; } = ""; public double BaselineQuantity { get; set; } public double CurrentQuantity { get; set; } public double Delta { get; set; } public double? DeltaPercent { get; set; } public string Unit { get; set; } = ""; }
}
