using System;
using System.Collections.Generic;

namespace KhimTools.QuantityTakeoff.Models
{
    public enum QsProgressStatus { NOT_STARTED, IN_PROGRESS, COMPLETE, ON_HOLD, NOT_APPLICABLE }
    public enum QsProgressMethod { ELEMENT_COMPLETE, ELEMENT_PERCENT, MEASURED_QUANTITY, MANUAL_QUANTITY, MODEL_STATUS }
    public sealed class QsContract { public string ContractId { get; set; } = Guid.NewGuid().ToString("N"); public string ContractNumber { get; set; } = ""; public string ProjectName { get; set; } = ""; public string Currency { get; set; } = "VND"; public decimal OriginalContractValue { get; set; } public decimal CurrentContractValue { get; set; } public decimal RetentionPercent { get; set; } public decimal RetentionLimitPercent { get; set; } public decimal AdvancePaymentAmount { get; set; } public decimal TaxPercent { get; set; } public string Status { get; set; } = "DRAFT"; public List<QsContractBoqItem> BoqItems { get; set; } = new List<QsContractBoqItem>(); }
    public sealed class QsContractBoqItem { public string ContractBoqItemId { get; set; } = Guid.NewGuid().ToString("N"); public string BoqCode { get; set; } = ""; public string Description { get; set; } = ""; public string WorkPackage { get; set; } = ""; public string Unit { get; set; } = ""; public double ContractQuantity { get; set; } public decimal UnitRate { get; set; } public decimal ContractAmount { get; set; } public double ApprovedVariationQuantity { get; set; } public decimal ApprovedVariationAmount { get; set; } public double CurrentContractQuantity => ContractQuantity + ApprovedVariationQuantity; public string Currency { get; set; } = "VND"; }
    public sealed class QsProgressPeriod { public string PeriodId { get; set; } = Guid.NewGuid().ToString("N"); public string ContractId { get; set; } = ""; public int PeriodNumber { get; set; } public string Name { get; set; } = ""; public DateTime StartDate { get; set; } public DateTime EndDate { get; set; } public DateTime ValuationDate { get; set; } public string Status { get; set; } = "OPEN"; public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
    public sealed class QsProgressMeasurement { public string MeasurementId { get; set; } = Guid.NewGuid().ToString("N"); public string PeriodId { get; set; } = ""; public string ContractBoqItemId { get; set; } = ""; public string ElementUniqueId { get; set; } = ""; public int CurrentElementId { get; set; } public double BaseQuantity { get; set; } public double MeasuredQuantity { get; set; } public double PreviousCumulativeQuantity { get; set; } public double CurrentPeriodQuantity { get; set; } public double CumulativeQuantity { get; set; } public double PercentComplete { get; set; } public QsProgressMethod MeasurementMethod { get; set; } public QsProgressStatus Status { get; set; } public string BoqCode { get; set; } = ""; public string Unit { get; set; } = ""; public string Notes { get; set; } = ""; }
    public sealed class QsPaymentCertificate { public string CertificateId { get; set; } = Guid.NewGuid().ToString("N"); public string ContractId { get; set; } = ""; public string PeriodId { get; set; } = ""; public string CertificateNumber { get; set; } = ""; public decimal PreviousCertifiedAmount { get; set; } public decimal GrossCurrentPeriodAmount { get; set; } public decimal GrossCumulativeAmount { get; set; } public decimal RetentionThisPeriod { get; set; } public decimal AdvanceRecoveryThisPeriod { get; set; } public decimal OtherDeductions { get; set; } public decimal Tax { get; set; } public decimal NetCurrentPayment { get; set; } public string Currency { get; set; } = "VND"; public string Status { get; set; } = "DRAFT"; public List<QsPaymentBoqLine> Lines { get; set; } = new List<QsPaymentBoqLine>(); }
    public sealed class QsPaymentBoqLine { public string ContractBoqItemId { get; set; } = ""; public double PreviousQuantity { get; set; } public double CurrentQuantity { get; set; } public double CumulativeQuantity { get; set; } public decimal PreviousValue { get; set; } public decimal CurrentValue { get; set; } public decimal CumulativeValue { get; set; } }
    public sealed class QsVariationOrder { public string VariationId { get; set; } = Guid.NewGuid().ToString("N"); public string VariationNumber { get; set; } = ""; public string Title { get; set; } = ""; public string Status { get; set; } = "DRAFT"; public decimal SubmittedValue { get; set; } public decimal ApprovedValue { get; set; } public List<QsVariationItem> Items { get; set; } = new List<QsVariationItem>(); }
    public sealed class QsVariationItem { public string VariationId { get; set; } = ""; public string BoqCode { get; set; } = ""; public double QuantityDelta { get; set; } public string Unit { get; set; } = ""; public decimal Rate { get; set; } public decimal Amount => (decimal)QuantityDelta * Rate; public string Source { get; set; } = ""; public List<string> RelatedUniqueIds { get; set; } = new List<string>(); }
}
