using System;
using System.Collections.Generic;

namespace KhimTools.QuantityTakeoff.Models
{
    public enum QsPricingStatus { PRICED, UNPRICED, UNIT_MISMATCH, RATE_MISSING, AMBIGUOUS_RATE, INVALID_QUANTITY, IGNORED }
    public enum QsAdjustmentType { Waste, Contingency, Escalation, Discount, Markup, Custom }
    public enum QsAdjustmentMethod { Percent, FixedAmount }
    public sealed class QsUnitRate { public string RateId { get; set; } = ""; public string BoqCode { get; set; } = ""; public string Description { get; set; } = ""; public string Unit { get; set; } = ""; public decimal BaseRate { get; set; } public string Currency { get; set; } = "VND"; public string RateSource { get; set; } = ""; public DateTime? EffectiveDate { get; set; } public string Region { get; set; } = ""; public string Supplier { get; set; } = ""; public string Reference { get; set; } = ""; public string Notes { get; set; } = ""; public bool IsActive { get; set; } = true; public decimal? LaborCost { get; set; } public decimal? MaterialCost { get; set; } public decimal? EquipmentCost { get; set; } public decimal? SubcontractCost { get; set; } public decimal? OtherCost { get; set; } }
    public sealed class QsCostAdjustment { public string AdjustmentId { get; set; } = Guid.NewGuid().ToString("N"); public string Name { get; set; } = ""; public QsAdjustmentType Type { get; set; } public QsAdjustmentMethod Method { get; set; } = QsAdjustmentMethod.Percent; public decimal Value { get; set; } public int Priority { get; set; } public string AppliesTo { get; set; } = "Project"; public bool Enabled { get; set; } = true; }
    public sealed class QsCostItem { public string BoqCode { get; set; } = ""; public string Description { get; set; } = ""; public double Quantity { get; set; } public string QuantityUnit { get; set; } = ""; public string RateId { get; set; } = ""; public decimal UnitRate { get; set; } public string RateUnit { get; set; } = ""; public decimal NormalizedQuantity { get; set; } public string Currency { get; set; } = "VND"; public decimal DirectCost { get; set; } public decimal WasteCost { get; set; } public decimal AdjustmentCost { get; set; } public decimal FinalCost { get; set; } public string Level { get; set; } = ""; public string WorkPackage { get; set; } = ""; public QsPricingStatus PricingStatus { get; set; } public List<string> SourceQuantityIds { get; } = new List<string>(); }
    public sealed class QsEstimate { public string EstimateId { get; set; } = Guid.NewGuid().ToString("N"); public string Name { get; set; } = ""; public string Revision { get; set; } = "R0"; public string Project { get; set; } = ""; public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public string Currency { get; set; } = "VND"; public string QuantitySnapshotId { get; set; } = ""; public string Status { get; set; } = "DRAFT"; public List<QsCostItem> Items { get; set; } = new List<QsCostItem>(); public decimal DirectCost { get; set; } public decimal Adjustments { get; set; } public decimal FinalCost { get; set; } }
    public sealed class QsCostDelta { public string BoqCode { get; set; } = ""; public decimal QuantityEffect { get; set; } public decimal RateEffect { get; set; } public decimal InteractionEffect { get; set; } public decimal TotalDelta => QuantityEffect + RateEffect + InteractionEffect; }
}
