using System;
using System.Collections.Generic;

namespace KhimTools.QuantityTakeoff.Models
{
    public sealed class QsReportingPeriod { public string PeriodId { get; set; } = Guid.NewGuid().ToString("N"); public string PeriodCode { get; set; } = ""; public string Name { get; set; } = ""; public DateTime StartDate { get; set; } public DateTime EndDate { get; set; } public DateTime DataDate { get; set; } public string Status { get; set; } = "OPEN"; public int Revision { get; set; } public DateTime? ClosedAt { get; set; } public string ClosedBy { get; set; } = ""; }
    public sealed class QsProjectKpi { public string KpiCode { get; set; } = ""; public string Name { get; set; } = ""; public string Category { get; set; } = ""; public decimal Value { get; set; } public string Unit { get; set; } = ""; public string Status { get; set; } = "N_A"; public string Trend { get; set; } = "N_A"; public decimal? PreviousValue { get; set; } public decimal? Variance { get; set; } public string DataSource { get; set; } = ""; public string Confidence { get; set; } = "UNKNOWN"; }
    public sealed class QsCostForecast { public decimal Budget { get; set; } public decimal ApprovedChanges { get; set; } public decimal CurrentBudget { get; set; } public decimal CommittedCost { get; set; } public decimal ActualCost { get; set; } public decimal CertifiedCost { get; set; } public decimal PaidCost { get; set; } public decimal UncommittedForecast { get; set; } public decimal PendingChangeExposure { get; set; } public decimal RiskAllowance { get; set; } public decimal ForecastFinalCost { get; set; } public decimal VarianceAtCompletion => Budget - ForecastFinalCost; public string Currency { get; set; } = "VND"; public string ForecastMethod { get; set; } = "COMMITTED_PLUS_FORECAST"; }
    public sealed class QsCashflowPoint { public string PeriodId { get; set; } = ""; public decimal PlannedCashOut { get; set; } public decimal ForecastCashOut { get; set; } public decimal CertifiedValue { get; set; } public decimal PaidValue { get; set; } public decimal CommittedValue { get; set; } public decimal CumulativePlanned { get; set; } public decimal CumulativeForecast { get; set; } public decimal CumulativePaid { get; set; } }
    public sealed class QsProjectHealth { public string CostHealth { get; set; } = "N_A"; public string ScheduleHealth { get; set; } = "N_A"; public string ProcurementHealth { get; set; } = "N_A"; public string CommercialHealth { get; set; } = "N_A"; public string RiskHealth { get; set; } = "N_A"; public string DataHealth { get; set; } = "N_A"; public string OverallState { get; set; } = "N_A"; public string Reason { get; set; } = ""; }
    public sealed class QsDataQualitySummary { public double ModelFreshness { get; set; } public double QuantityCoverage { get; set; } public double BoqCoverage { get; set; } public double PricingCoverage { get; set; } public double ScheduleMappingCoverage { get; set; } public double ProgressCoverage { get; set; } public double ProcurementCoverage { get; set; } public bool IsIncomplete => BoqCoverage < 90 || PricingCoverage < 90 || ScheduleMappingCoverage < 90; }
    public sealed class QsProjectControlsSnapshot { public string SnapshotId { get; set; } = Guid.NewGuid().ToString("N"); public string ProjectId { get; set; } = ""; public string ProjectName { get; set; } = ""; public string ReportingPeriodId { get; set; } = ""; public DateTime DataDate { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public string Currency { get; set; } = "VND"; public List<QsProjectKpi> Kpis { get; set; } = new List<QsProjectKpi>(); public QsCostForecast CostForecast { get; set; } = new QsCostForecast(); public QsProjectHealth Health { get; set; } = new QsProjectHealth(); public QsDataQualitySummary DataQuality { get; set; } = new QsDataQualitySummary(); }
}
