using System;
using System.Collections.Generic;

namespace KhimTools.QuantityTakeoff.Models
{
    public sealed class KqsModelIdentity { public string ModelId { get; set; } = Guid.NewGuid().ToString("N"); public string ProjectId { get; set; } = ""; public string ModelName { get; set; } = ""; public string Discipline { get; set; } = ""; public string SourceType { get; set; } = "REVIT"; public string VersionReference { get; set; } = ""; public DateTime? LastScan { get; set; } }
    public sealed class KqsAuditEvent { public string AuditId { get; set; } = Guid.NewGuid().ToString("N"); public string ProjectId { get; set; } = ""; public string EntityType { get; set; } = ""; public string EntityId { get; set; } = ""; public string Action { get; set; } = ""; public DateTime TimestampUtc { get; set; } = DateTime.UtcNow; public string UserId { get; set; } = ""; public string OldValueSummary { get; set; } = ""; public string NewValueSummary { get; set; } = ""; }
    public sealed class KqsChangeEnvelope { public string ChangeId { get; set; } = Guid.NewGuid().ToString("N"); public string ProjectId { get; set; } = ""; public string EntityType { get; set; } = ""; public string EntityId { get; set; } = ""; public string Operation { get; set; } = "UPDATE"; public long BaseVersion { get; set; } public long NewVersion { get; set; } public Dictionary<string,string> ChangedFields { get; set; } = new Dictionary<string,string>(); public DateTime TimestampUtc { get; set; } = DateTime.UtcNow; public string UserId { get; set; } = ""; public string DeviceId { get; set; } = ""; }
    public sealed class KqsSyncConflict { public string ConflictId { get; set; } = Guid.NewGuid().ToString("N"); public string EntityType { get; set; } = ""; public string EntityId { get; set; } = ""; public long BaseVersion { get; set; } public long LocalVersion { get; set; } public long RemoteVersion { get; set; } public string Status { get; set; } = "OPEN"; public List<string> ConflictFields { get; set; } = new List<string>(); }
    public sealed class KqsProjectStoreData { public string SchemaVersion { get; set; } = "1"; public string ProjectId { get; set; } = Guid.NewGuid().ToString("N"); public string ProjectName { get; set; } = ""; public long SyncToken { get; set; } public List<KqsAuditEvent> Audit { get; set; } = new List<KqsAuditEvent>(); public List<KqsChangeEnvelope> PendingChanges { get; set; } = new List<KqsChangeEnvelope>(); public List<KqsModelIdentity> Models { get; set; } = new List<KqsModelIdentity>(); }
}
