namespace KhimTools.ModifyObjects.Core
{
    public enum ModifyObjectStatus
    {
        READY, NO_CHANGE, INVALID_SELECTION, UNSUPPORTED_ELEMENT, INVALID_GEOMETRY,
        INVALID_SPLIT_POINT, INVALID_JOIN_PAIR, NO_INTERSECTION, ALREADY_JOINED,
        NOT_JOINED, CONSTRAINT_BLOCKED, GROUP_CONSTRAINED, DESIGN_OPTION_BLOCKED,
        WORKSHARING_BLOCKED, HOST_DEPENDENCY_RISK, CREATED, MODIFIED, DELETED_SOURCE,
        PARTIAL, FAILED, POST_VERIFY_FAILED, COLUMN_GEOMETRY_UNSUPPORTED,
        ATTACHED_COLUMN_UNSUPPORTED, PARAMETER_CONFLICT, BEAM_GEOMETRY_UNSUPPORTED,
        OPENING_CROSSES_SPLIT, HOSTED_CONTENT_RISK, OPENING_CONFLICT,
        SHAPE_EDITED_FLOOR_UNSUPPORTED, COPY_UNSUPPORTED, STALE_PLAN,
        SLAB_SPLIT_CAPABILITY_UNSUPPORTED, BASE_LEVEL_MISSING, INVALID_BASE_OFFSET,
        PINNED, LINKED_ELEMENT, READ_ONLY, PREVIEW_ONLY
    }
}
