using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;
using Autodesk.Revit.DB;
using KhimTools.Core;
using KhimTools.Core.UI;
using KhimTools.ParameterManager.Models;
using KhimTools.ParameterManager.Services;
using KhimTools.ParameterTransfer.Models;
using WinControl = System.Windows.Forms.Control;

namespace KhimTools.ParameterManager.Forms
{
    public sealed class ParameterManagerForm : KTBaseForm
    {
        private readonly Document _doc; private readonly ElementId _activeViewId; private readonly IList<ElementId> _selectedIds;
        private readonly ComboBox _scope = new ComboBox(); private readonly ComboBox _parameterScope = new ComboBox(); private readonly ComboBox _category = new ComboBox(); private readonly ComboBox _parameter = new ComboBox(); private readonly ComboBox _rule = new ComboBox(); private readonly TextBox _value = new TextBox(); private readonly TextBox _search = new TextBox(); private readonly TextBox _familyFilter = new TextBox(); private readonly TextBox _typeFilter = new TextBox(); private readonly CheckBox _onlyMissing = new CheckBox(); private readonly CheckBox _strict = new CheckBox(); private readonly DataGridView _preview = new DataGridView(); private readonly Label _status = new Label(); private readonly List<ParameterDescriptor> _descriptors = new List<ParameterDescriptor>(); private Button _applyButton; private ParameterManagerPlan _currentPlan;
        public ParameterManagerRequest Request { get; private set; }
        public ParameterManagerPlan Plan { get { return _currentPlan; } private set { _currentPlan = value; } }
        public ParameterManagerForm(Document doc, ElementId activeViewId, IList<ElementId> selectedIds) { _doc = doc; _activeViewId = activeViewId ?? ElementId.InvalidElementId; _selectedIds = selectedIds ?? new List<ElementId>(); KhimUiStyle.ApplyFormTheme(this); BuildLayout(); LoadDocument(); }
        private ParameterManagerForm(bool preview) { _doc = null; _activeViewId = ElementId.InvalidElementId; _selectedIds = new List<ElementId>(); KhimUiStyle.ApplyFormTheme(this); BuildLayout(); }
        internal static ParameterManagerForm CreateLayoutPreview() { return new ParameterManagerForm(true); }
        private void BuildLayout()
        {
            Text = "K-TOOLS - Parameter Manager 2.0"; Width = 1320; Height = 820; MinimumSize = new Size(1000, 650); StartPosition = FormStartPosition.CenterScreen; Font = new Font("Segoe UI", 9F);
            var root = new TableLayoutPanel { Dock = DockStyle.Fill, Padding = new Padding(10), ColumnCount = 2, RowCount = 3 }; root.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 390)); root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100)); root.RowStyles.Add(new RowStyle(SizeType.Absolute, 150)); root.RowStyles.Add(new RowStyle(SizeType.Percent, 100)); root.RowStyles.Add(new RowStyle(SizeType.Absolute, 54));
            var controls = new TableLayoutPanel { Dock = DockStyle.Fill, ColumnCount = 4, RowCount = 4, Padding = new Padding(4) }; controls.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 120)); controls.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50)); controls.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 120)); controls.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50));
            _scope.DropDownStyle = ComboBoxStyle.DropDownList; _scope.Items.AddRange(Enum.GetValues(typeof(ElementScopeMode)).Cast<object>().ToArray()); _scope.SelectedItem = ElementScopeMode.CURRENT_SELECTION; _scope.SelectedIndexChanged += (s, e) => LoadDocument();
            _parameterScope.DropDownStyle = ComboBoxStyle.DropDownList; _parameterScope.Items.AddRange(Enum.GetValues(typeof(ParameterScopeMode)).Cast<object>().ToArray()); _parameterScope.SelectedItem = ParameterScopeMode.INSTANCE; _parameterScope.SelectedIndexChanged += (s, e) => LoadDocument();
            _category.DropDownStyle = ComboBoxStyle.DropDownList; _parameter.DropDownStyle = ComboBoxStyle.DropDownList; _rule.DropDownStyle = ComboBoxStyle.DropDownList; _rule.Items.AddRange(Enum.GetValues(typeof(ParameterRuleType)).Cast<object>().ToArray()); _rule.SelectedItem = ParameterRuleType.SET_VALUE; _onlyMissing.Text = "Only if missing"; _strict.Text = "Strict all-or-nothing";
            AddField(controls, "Element scope", _scope, 0, 0); AddField(controls, "Parameter target", _parameterScope, 2, 0); AddField(controls, "Category", _category, 0, 1); AddField(controls, "Parameter", _parameter, 2, 1); AddField(controls, "Rule", _rule, 0, 2); AddField(controls, "Value / Find", _value, 2, 2); controls.Controls.Add(_onlyMissing, 1, 2); controls.Controls.Add(_strict, 3, 2);
            var filterBar = new FlowLayoutPanel { Dock = DockStyle.Fill, WrapContents = false, AutoScroll = true }; _search.Width = 150; _familyFilter.Width = 150; _typeFilter.Width = 150; _search.TextChanged += (s, e) => ApplyGridFilter(); _familyFilter.TextChanged += (s, e) => ApplyGridFilter(); _typeFilter.TextChanged += (s, e) => ApplyGridFilter(); filterBar.Controls.Add(new Label { Text = "Search", AutoSize = true, Margin = new Padding(4, 8, 3, 4) }); filterBar.Controls.Add(_search); filterBar.Controls.Add(new Label { Text = "Family", AutoSize = true, Margin = new Padding(8, 8, 3, 4) }); filterBar.Controls.Add(_familyFilter); filterBar.Controls.Add(new Label { Text = "Type", AutoSize = true, Margin = new Padding(8, 8, 3, 4) }); filterBar.Controls.Add(_typeFilter); var selectAll = new Button { Text = "Select All", Width = 85 }; selectAll.Click += SelectAllVisible; var resetRules = new Button { Text = "Reset to Rules", Width = 105 }; resetRules.Click += (s, e) => PreviewClicked(s, e); filterBar.Controls.Add(selectAll); filterBar.Controls.Add(resetRules); controls.Controls.Add(filterBar, 0, 3); controls.SetColumnSpan(filterBar, 4); root.Controls.Add(controls, 0, 0); root.SetColumnSpan(controls, 2);
            _preview.Dock = DockStyle.Fill; _preview.AllowUserToAddRows = false; _preview.RowHeadersVisible = false; _preview.AutoGenerateColumns = false; _preview.Columns.Add(new DataGridViewCheckBoxColumn { HeaderText = "Use", Width = 45 }); _preview.Columns.Add("Element", "Element"); _preview.Columns.Add("Category", "Category"); _preview.Columns.Add("FamilyType", "Family / Type"); _preview.Columns.Add("Current", "Current"); _preview.Columns.Add("Proposed", "Proposed"); _preview.Columns.Add("Status", "Status"); _preview.Columns.Add("Action", "Action"); _preview.CellEndEdit += PreviewCellEndEdit; root.Controls.Add(_preview, 0, 1); root.SetColumnSpan(_preview, 2);
            _status.Text = "Preview is read-only; Apply writes only after preflight."; _status.Dock = DockStyle.Fill; root.Controls.Add(_status, 0, 2); root.SetColumnSpan(_status, 2); var buttons = new FlowLayoutPanel { Dock = DockStyle.Fill, FlowDirection = FlowDirection.RightToLeft }; _applyButton = new Button { Text = "Apply", Width = 100, Enabled = false }; _applyButton.Click += ApplyClicked; var preview = new Button { Text = "Preview", Width = 100 }; preview.Click += PreviewClicked; var refresh = new Button { Text = "Refresh", Width = 100 }; refresh.Click += (s, e) => { Plan = null; LoadDocument(); }; var cancel = new Button { Text = "Cancel", Width = 100, DialogResult = DialogResult.Cancel }; buttons.Controls.AddRange(new WinControl[] { _applyButton, preview, refresh, cancel }); Controls.Add(root); root.Controls.Add(buttons, 0, 2); root.SetColumnSpan(buttons, 2); CancelButton = cancel;
        }
        private static void AddField(TableLayoutPanel panel, string label, Control control, int col, int row) { panel.Controls.Add(new Label { Text = label, AutoSize = true, Anchor = AnchorStyles.Left, Margin = new Padding(4, 8, 4, 4) }, col, row); control.Dock = DockStyle.Fill; panel.Controls.Add(control, col + 1, row); }
        private void LoadDocument()
        {
            if (_doc == null) return; _category.Items.Clear(); foreach (ElementId id in ParameterElementCollector.CollectCategories(_doc, _activeViewId)) { Category c = Category.GetCategory(_doc, id); if (c != null) _category.Items.Add(new CategoryChoice(id, c.Name)); } if (_category.Items.Count > 0 && _category.SelectedIndex < 0) _category.SelectedIndex = 0;
            ParameterManagerRequest request = BuildRequest(false); IList<Element> elements = ParameterElementCollector.Collect(_doc, request); _descriptors.Clear(); _descriptors.AddRange(ParameterDiscoveryService.Discover(_doc, elements, (ParameterScopeMode)_parameterScope.SelectedItem)); _parameter.Items.Clear(); foreach (ParameterDescriptor descriptor in _descriptors) _parameter.Items.Add(descriptor); if (_parameter.Items.Count > 0) _parameter.SelectedIndex = 0;
        }
        private ParameterManagerRequest BuildRequest(bool previewOnly)
        {
            var request = new ParameterManagerRequest { Document = _doc, Scope = _scope.SelectedItem is ElementScopeMode ? (ElementScopeMode)_scope.SelectedItem : ElementScopeMode.CURRENT_SELECTION, ParameterScope = _parameterScope.SelectedItem is ParameterScopeMode ? (ParameterScopeMode)_parameterScope.SelectedItem : ParameterScopeMode.INSTANCE, ActiveViewId = _activeViewId, PreviewOnly = previewOnly, Options = new ParameterManagerOptions { AllOrNothing = _strict.Checked, PrefixOnlyIfMissing = _onlyMissing.Checked, SuffixOnlyIfMissing = _onlyMissing.Checked } };
            foreach (ElementId id in _selectedIds) request.ElementIds.Add(id); CategoryChoice choice = _category.SelectedItem as CategoryChoice; if (choice != null) request.CategoryId = choice.Id; ParameterDescriptor descriptor = _parameter.SelectedItem as ParameterDescriptor; if (descriptor != null) request.SelectedParameterKey = descriptor.Key; request.Rules.Add(new ParameterRule { RuleType = _rule.SelectedItem is ParameterRuleType ? (ParameterRuleType)_rule.SelectedItem : ParameterRuleType.SET_VALUE, Value = _value.Text, OnlyIfMissing = _onlyMissing.Checked }); return request;
        }
        private void PreviewClicked(object sender, EventArgs e) { var manual = Plan == null ? new Dictionary<int, ParameterEditItem>() : Plan.Items.Where(i => i.IsManualOverride).ToDictionary(i => i.ElementId.IntegerValue, i => i); Request = BuildRequest(true); Plan = ParameterManagerPlanner.BuildPlan(_doc, Request); foreach (ParameterEditItem item in Plan.Items) { ParameterEditItem prior; if (manual.TryGetValue(item.ElementId.IntegerValue, out prior)) { item.ProposedValue = ParameterValueParser.Clone(prior.ProposedValue); item.IsManualOverride = true; item.Status = ParameterManagerStatus.READY; item.Action = ParameterManagerAction.UPDATE; } } _preview.Rows.Clear(); foreach (ParameterEditItem item in Plan.Items) { int row = _preview.Rows.Add(item.IsSelected, item.ElementId.IntegerValue, item.CategoryName, item.FamilyName + " / " + item.TypeName, item.CurrentDisplay, item.ProposedDisplay, item.Status, item.Action); _preview.Rows[row].Tag = item; } _applyButton.Enabled = Plan.Items.Any(i => i.IsSelected && i.Action == ParameterManagerAction.UPDATE && i.Status != ParameterManagerStatus.INVALID_REGEX && i.Status != ParameterManagerStatus.PARAMETER_READ_ONLY && i.Status != ParameterManagerStatus.PARAMETER_PROTECTED); _status.Text = "Preview: " + Plan.Items.Count + " target(s), " + Plan.Warnings.Count + " warning(s). No model writes occurred."; }
        private void ApplyClicked(object sender, EventArgs e) { if (Plan == null) PreviewClicked(sender, e); if (Plan == null || !_applyButton.Enabled) { _status.Text = "No executable targets remain after preflight."; return; } Request.PreviewOnly = false; foreach (DataGridViewRow row in _preview.Rows) if (row.Tag is ParameterEditItem item) item.IsSelected = row.Cells[0].Value is bool && (bool)row.Cells[0].Value; DialogResult = DialogResult.OK; Close(); }
        private void SelectAllVisible(object sender, EventArgs e) { foreach (DataGridViewRow row in _preview.Rows) if (row.Visible) row.Cells[0].Value = true; }
        private void ApplyGridFilter() { foreach (DataGridViewRow row in _preview.Rows) { string search = Convert.ToString(row.Cells[1].Value) + " " + Convert.ToString(row.Cells[2].Value) + " " + Convert.ToString(row.Cells[3].Value); bool visible = (string.IsNullOrWhiteSpace(_search.Text) || search.IndexOf(_search.Text, StringComparison.OrdinalIgnoreCase) >= 0) && (string.IsNullOrWhiteSpace(_familyFilter.Text) || Convert.ToString(row.Cells[3].Value).IndexOf(_familyFilter.Text, StringComparison.OrdinalIgnoreCase) >= 0) && (string.IsNullOrWhiteSpace(_typeFilter.Text) || Convert.ToString(row.Cells[3].Value).IndexOf(_typeFilter.Text, StringComparison.OrdinalIgnoreCase) >= 0); row.Visible = visible; } }
        private void PreviewCellEndEdit(object sender, DataGridViewCellEventArgs e) { if (e.RowIndex < 0 || e.ColumnIndex != 5) return; ParameterEditItem item = _preview.Rows[e.RowIndex].Tag as ParameterEditItem; if (item == null) return; item.IsManualOverride = true; string text = Convert.ToString(_preview.Rows[e.RowIndex].Cells[e.ColumnIndex].Value); ParameterValueSnapshot parsed; ParameterManagerStatus status; string error; if (ParameterValueParser.TryParse(item.CurrentValue, text, Request == null ? null : Request.Options, out parsed, out status, out error)) { item.ProposedValue = parsed; item.Status = ParameterManagerStatus.READY; item.Action = ParameterManagerAction.UPDATE; } else { item.Status = status; item.Action = ParameterManagerAction.BLOCKED; item.Message = error; } }
        private sealed class CategoryChoice { public ElementId Id { get; private set; } public string Name { get; private set; } public CategoryChoice(ElementId id, string name) { Id = id; Name = name; } public override string ToString() { return Name; } }
    }
}
