namespace KhimTools.DimensionTools.Models
{
    public enum DimensionOperation { GRID, COLUMN, BEAM, FOUNDATION, OPENING, ELEVATION, SPOT_ELEVATION, QUICK, GENERAL, CUT, JOIN, REMOVE_ZERO, MOVE_TEXT }
    public enum DimensionAxis { AUTO, HORIZONTAL_IN_VIEW, VERTICAL_IN_VIEW, PICK_LINE }
    public enum DimensionReferenceRole { GRID, COLUMN_FACE, BEAM_FACE, FOUNDATION_FACE, OPENING_EDGE, LEVEL, WALL_FACE, GENERIC_FACE, CENTER }
}
