namespace KhimTools.DimensionTools.Models
{
    public enum DimensionStatus
    {
        READY, NO_CHANGE, INVALID_SELECTION, UNSUPPORTED_VIEW_TYPE, UNSUPPORTED_ELEMENT,
        REFERENCE_NOT_FOUND, REFERENCE_INVALID, REFERENCE_NOT_PARALLEL, REFERENCE_NOT_COPLANAR,
        REFERENCE_DUPLICATE, INSUFFICIENT_REFERENCES, INVALID_DIMENSION_AXIS, INVALID_DIMENSION_LINE,
        DIMENSION_TYPE_MISSING, DIMENSION_TYPE_INVALID, STALE_REFERENCE, STALE_DIMENSION_PLAN,
        CENTER_REFERENCE_UNAVAILABLE, CYLINDRICAL_FACE_UNSUPPORTED, CURVED_GRID_UNSUPPORTED,
        CURVED_BEAM_UNSUPPORTED, FOUNDATION_TYPE_UNSUPPORTED, AMBIGUOUS_REFERENCE_STRATEGY,
        DIMENSIONS_INCOMPATIBLE, EQUALITY_CONSTRAINT_RISK, CONSTRAINT_DIMENSION_UNSUPPORTED,
        MANUAL_OVERRIDE_RISK, TEXT_LAYOUT_NOT_FULLY_PRESERVED, CREATED, UPDATED, PARTIAL,
        SKIPPED, FAILED, POST_VERIFY_FAILED, PINNED, PINNED_DIMENSION, REPLACED
    }
}
