$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$featureRoot = Join-Path $root 'KhimTools\Tools\KhimGen\FilterManager'
$checks = 0
function Read-Feature([string]$relative) { $path = Join-Path $featureRoot $relative; if (-not (Test-Path -LiteralPath $path)) { throw "FAIL: missing FilterManager file $relative" }; return Get-Content -LiteralPath $path -Raw }
function Assert-Text([string]$text, [string]$needle, [string]$label) { if ($text.IndexOf($needle, [StringComparison]::Ordinal) -lt 0) { throw "FAIL: $label" }; $script:checks++ }
function Assert-NotText([string]$text, [string]$needle, [string]$label) { if ($text.IndexOf($needle, [StringComparison]::Ordinal) -ge 0) { throw "FAIL: $label" }; $script:checks++ }
$command = Read-Feature 'Commands\CmdFilterManager.cs'; $form = Read-Feature 'Forms\FilterManagerForm.cs'
$models = (Get-ChildItem (Join-Path $featureRoot 'Models') -Filter '*.cs' -Recurse | ForEach-Object { Get-Content $_.FullName -Raw }) -join "`n"
$services = (Get-ChildItem (Join-Path $featureRoot 'Services') -Filter '*.cs' -Recurse | ForEach-Object { Get-Content $_.FullName -Raw }) -join "`n"
$all = $command + $form + $models + $services
Assert-Text $command 'class CmdFilterManager : IExternalCommand' 'public command'
Assert-Text $command 'Transaction(TransactionMode.Manual)' 'manual transaction'
Assert-Text $form 'Filter Manager 2.0' 'form title'; Assert-Text $form 'Preview' 'preview action'; Assert-Text $form 'Apply' 'apply action'; Assert-Text $form 'Cancel' 'cancel action'; Assert-Text $form 'SelectedIndex = -1' 'no arbitrary source auto-selection'; Assert-Text $form 'MinimumSize' 'DPI-safe minimum form size'; Assert-Text $form 'TableLayoutPanel' 'responsive form layout'; Assert-Text $form 'explicit source' 'explicit source wording'; Assert-Text $form 'EXACT_SYNC' 'advanced exact mode'; Assert-Text $form 'MERGE_SELECTED_FILTERS' 'merge default mode'
Assert-Text $models 'FilterDefinitionInfo' 'definition model'; Assert-Text $models 'AppliedFilterState' 'applied state model'; Assert-Text $models 'FilterCopyRequest' 'request model'; Assert-Text $models 'FilterCopyPlan' 'plan model'; Assert-Text $models 'FilterTargetPlan' 'target plan model'; Assert-Text $models 'FilterSyncOptions' 'sync options'; Assert-Text $models 'FilterManagerStatus' 'status model'; Assert-Text $models 'FilterManagerResult' 'result model'; Assert-Text $models 'FilterPreflightResult' 'preflight result model'; Assert-Text $models 'GraphicOverrideSnapshot' 'OGS snapshot model'; Assert-Text $models 'FilterId' 'ElementId identity'; Assert-Text $models 'UniqueId' 'UniqueId identity'; Assert-Text $models 'SourceViewId' 'source view identity'; Assert-Text $models 'StateFingerprint' 'state fingerprint'; Assert-Text $models 'ViewTemplateControlStatus' 'template status model'
Assert-Text $services 'ParameterFilterElement' 'ParameterFilterElement support'; Assert-Text $services 'SelectionFilterElement' 'SelectionFilterElement support'; Assert-Text $services 'ViewFilterApiAdapter' 'API compatibility adapter'; Assert-Text $services 'GetAppliedFilters' 'applied filter API'; Assert-Text $services 'GetOrderedFilters' 'ordered filter API'; Assert-Text $services 'GetEnabled' 'enabled capability'; Assert-Text $services 'SetEnabled' 'enabled setter capability'; Assert-Text $services 'SupportsEnabledState' 'enabled capability flag'; Assert-Text $services 'GetVisibility' 'visibility read'; Assert-Text $services 'SetVisibility' 'visibility write'; Assert-Text $services 'GetOverrides' 'OGS read'; Assert-Text $services 'SetOverrides' 'OGS write'; Assert-Text $services 'OverrideGraphicSettings' 'OGS type'; Assert-Text $services 'GraphicOverrideSnapshotService' 'OGS snapshot service'; Assert-Text $services 'Fingerprint' 'normalized fingerprint'; Assert-Text $services 'ViewTemplateId' 'template guard'; Assert-Text $services 'GetTemplateParameterIds' 'template controlled parameter API'; Assert-Text $services 'GetNonControlledTemplateParameterIds' 'template non-controlled API'
Assert-Text $all 'MERGE_SELECTED_FILTERS' 'merge strategy'; Assert-Text $all 'EXACT_SYNC' 'exact strategy'; Assert-Text $services 'RemoveFilter' 'remove from target view'; Assert-Text $services 'AddExistingFilter' 'add existing filter action'; Assert-Text $services 'RemoveAppliedFilter' 'remove applied filter action'; Assert-Text $form 'Add Existing Filter' 'add existing filter UI'; Assert-Text $form 'Remove from View' 'remove from view UI'; Assert-Text $form 'Toggle Visibility' 'visibility action UI'; Assert-Text $form 'Toggle Enabled' 'enabled action UI'; Assert-Text $form 'Copy/Paste Graphic Overrides' 'OGS action UI'; Assert-Text $form 'Reset selected state' 'reset state UI'; Assert-Text $all 'AddMissingFilters' 'add missing option'; Assert-Text $all 'ClearOverrides' 'clear override option'; Assert-Text $all 'CLEAR_FILTER_OVERRIDES' 'clear override status'; Assert-Text $all 'EXACT_SYNC_REMOVE_REQUIRED' 'exact removal classification'; Assert-Text $all 'ADD_FILTER_REQUIRED' 'missing filter classification'; Assert-Text $all 'STATE_DIFF' 'state difference classification'; Assert-Text $all 'OVERRIDE_DIFF' 'override difference classification'; Assert-Text $all 'VISIBILITY_DIFF' 'visibility difference classification'; Assert-Text $all 'ENABLED_DIFF' 'enabled difference classification'; Assert-Text $all 'ORDER_DIFF' 'order difference classification'; Assert-Text $all 'STALE_SYNC_PLAN' 'stale plan classification'; Assert-Text $all 'STALE_FILTER_PLAN' 'filter stale plan status'; Assert-Text $all 'TARGET_FILTERS_CONTROLLED_BY_TEMPLATE' 'template safety block'; Assert-Text $all 'FILTER_ENABLED_STATE_UNSUPPORTED' 'enabled unsupported classification'; Assert-Text $services 'Transaction transaction' 'per-target transaction isolation'; Assert-Text $services 'FilterPreflightService' 'preflight service'; Assert-Text $services 'FilterVerificationService' 'post verification service'; Assert-Text $services 'VerifyGlobalDefinitionsUnchanged' 'global definition verification'; Assert-NotText $services 'doc.Delete' 'no global filter delete'; Assert-NotText $services 'catch { }' 'no silent catches'; Assert-NotText $services '.First()' 'no arbitrary source First'
$fixture = Get-Content (Join-Path $root 'KhimTools\Tools\KhimGen\RuntimeQa\Fixtures\FilterManagerRuntimeFixture.cs') -Raw; Assert-Text $fixture 'FilterManagerRuntimeFixture' 'runtime fixture'; Assert-Text $fixture 'FilterCopyPlanner.BuildPlan' 'fixture planner'; Assert-Text $fixture 'FilterExecutionService.Execute' 'fixture execution'; Assert-Text $fixture 'FilterVerificationService.VerifyTarget' 'fixture target verification'; Assert-Text $fixture 'VerifySourceUnchanged' 'fixture source verification'; Assert-Text $fixture 'VerifyGlobalDefinitionsUnchanged' 'fixture global verification'; Assert-Text $fixture 'Block(' 'exact blocked prerequisite'; Assert-Text $fixture 'TransactionGroup' 'outer rollback boundary'
$registry = Get-Content (Join-Path $root 'KhimTools\Tools\KhimGen\RuntimeQa\Core\RuntimeQaRegistry.cs') -Raw; Assert-Text $registry 'FilterManagerRuntimeFixture' 'fixture registry'; $ribbon = Get-Content (Join-Path $root 'KhimTools\Core\RibbonBuilder.cs') -Raw; Assert-Text $ribbon 'KhimTools.FilterManager.Commands.CmdFilterManager' 'ribbon registration'
foreach ($file in (Get-ChildItem -LiteralPath $featureRoot -Recurse -Filter '*.cs')) { $text = Get-Content -LiteralPath $file.FullName -Raw; if ($text -match '(?ms)catch\s*\{\s*\}') { throw "FAIL: silent catch in $($file.FullName)" }; $checks++ }
Write-Output "PASS: $checks Filter Manager Stage 3.4 static checks. No Revit model operation executed."
