$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$featureRoot = Join-Path $root 'KhimTools\Tools\KhimGen\TitleBlockSync'
$checks = 0
function Read-Feature([string]$relative) { $path = Join-Path $featureRoot $relative; if (-not (Test-Path -LiteralPath $path)) { throw "FAIL: missing TitleBlockSync file $relative" }; return Get-Content -LiteralPath $path -Raw }
function Assert-Text([string]$text, [string]$needle, [string]$label) { if ($text.IndexOf($needle, [StringComparison]::Ordinal) -lt 0) { throw "FAIL: $label" }; $script:checks++ }
function Assert-NotText([string]$text, [string]$needle, [string]$label) { if ($text.IndexOf($needle, [StringComparison]::Ordinal) -ge 0) { throw "FAIL: $label" }; $script:checks++ }
$command = Read-Feature 'Commands\CmdTitleBlockSync.cs'; $form = Read-Feature 'Forms\TitleBlockSyncForm.cs'; $models = (Get-ChildItem (Join-Path $featureRoot 'Models') -Filter '*.cs' -Recurse | ForEach-Object { Get-Content $_.FullName -Raw }) -join "`n"; $services = (Get-ChildItem (Join-Path $featureRoot 'Services') -Filter '*.cs' -Recurse | ForEach-Object { Get-Content $_.FullName -Raw }) -join "`n"
Assert-Text $command 'class CmdTitleBlockSync : IExternalCommand' 'public command'
Assert-Text $form 'Title Block Sync 2.0' 'form title'; Assert-Text $form 'Preview' 'preview action'; Assert-Text $form 'Sync' 'sync action'; Assert-Text $form 'Close' 'cancel action'; Assert-Text $form 'SelectedIndex = -1' 'no silent source auto-selection'; Assert-Text $form 'source excluded' 'source exclusion'; Assert-Text $form 'MinimumSize' 'DPI-safe minimum form size'; Assert-Text $form 'TableLayoutPanel' 'responsive form layout'
Assert-Text $services 'TitleBlockCollector' 'collector'; Assert-Text $services 'ParameterTransferService' 'neutral shared core'; Assert-Text $services 'ParameterKey' 'stable parameter key'; Assert-Text $services 'IsShared' 'shared GUID identity'; Assert-Text $services 'BuiltInParameter' 'built-in identity'; Assert-Text $services 'GetDataType' 'data/spec identity'; Assert-Text $services 'ElementId' 'ElementId handling'; Assert-Text $services 'UNSAFE_ELEMENT_REFERENCE' 'ElementId safety block'; Assert-Text $services 'ChangeTypeId' 'actual type change'; Assert-Text $services 'SourceRevisionFingerprint' 'revision fingerprint'; Assert-Text $services 'SHEET_NUMBER' 'sheet number protection'; Assert-Text $services 'SHEET_NAME' 'sheet name protection'; Assert-Text $services 'revision' 'revision-managed protection'; Assert-Text $services 'GLOBAL_PROJECT_PARAMETER' 'ProjectInformation/global parameter protection'; Assert-Text $models 'TitleBlockSyncPlan' 'plan model'; Assert-Text $models 'STALE_SYNC_PLAN' 'stale-plan status'; Assert-Text $models 'TitleBlockSyncPreflightResult' 'preflight model'; Assert-Text $services 'TransactionGroup' 'transaction group'; Assert-Text $services 'Transaction transaction' 'per-target transaction'; Assert-Text $services 'POST_VERIFY_FAILED' 'post-verify failure'; Assert-Text $services 'AllowPartialTarget' 'strict/partial mode'; Assert-Text $services 'OverwriteBlankSource' 'blank source policy'; Assert-NotText $services 'catch { }' 'no silent catches'; Assert-NotText $services '.First()' 'no arbitrary source First'; Assert-NotText $services '.FirstOrDefault()' 'no arbitrary source FirstOrDefault'
$sheetCopy = Get-Content (Join-Path $root 'KhimTools\Tools\KhimGen\SheetCopy\Services\SheetCopyParameterService.cs') -Raw; Assert-Text $sheetCopy 'ParameterTransferService' 'SheetCopy shared core integration'; Assert-Text $sheetCopy 'AllowElementId = false' 'SheetCopy ElementId safety'
$fixturePath = Join-Path $root 'KhimTools\Tools\KhimGen\RuntimeQa\Fixtures\TitleBlockSyncRuntimeFixture.cs'; $fixture = Get-Content $fixturePath -Raw; Assert-Text $fixture 'TitleBlockSyncPlanner.BuildPlan' 'runtime fixture planner'; Assert-Text $fixture 'TitleBlockSyncExecutionService.Execute' 'runtime fixture execution'; Assert-Text $fixture 'Block(' 'fixture prerequisite blocking'
$registry = Get-Content (Join-Path $root 'KhimTools\Tools\KhimGen\RuntimeQa\Core\RuntimeQaRegistry.cs') -Raw; Assert-Text $registry 'TitleBlockSyncRuntimeFixture' 'fixture registry'; $ribbon = Get-Content (Join-Path $root 'KhimTools\Core\RibbonBuilder.cs') -Raw; Assert-Text $ribbon 'KhimTools.TitleBlockSync.Commands.CmdTitleBlockSync' 'ribbon command registration'
foreach ($file in (Get-ChildItem -LiteralPath $featureRoot -Recurse -Filter '*.cs')) { $text = Get-Content -LiteralPath $file.FullName -Raw; if ($text -match '(?ms)catch\s*\{\s*\}') { throw "FAIL: silent catch in $($file.FullName)" }; $checks++ }
Write-Output "PASS: $checks Title Block Sync Stage 3.3 static checks. No Revit model operation executed."
