$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$featureRoot = Join-Path $root 'KhimTools\Tools\KhimGen\ParameterManager'
$checks = 0
function Read-Feature([string]$relative) { $path = Join-Path $featureRoot $relative; if (-not (Test-Path -LiteralPath $path)) { throw "FAIL: missing Parameter Manager file $relative" }; return Get-Content -LiteralPath $path -Raw }
function Assert-Text([string]$text, [string]$needle, [string]$label) { if ($text.IndexOf($needle, [StringComparison]::Ordinal) -lt 0) { throw "FAIL: $label" }; $script:checks++ }
function Assert-NotText([string]$text, [string]$needle, [string]$label) { if ($text.IndexOf($needle, [StringComparison]::Ordinal) -ge 0) { throw "FAIL: $label" }; $script:checks++ }
$command = Read-Feature 'Commands\CmdParameterManager.cs'; $form = Read-Feature 'Forms\ParameterManagerForm.cs'
$models = (Get-ChildItem (Join-Path $featureRoot 'Models') -Filter '*.cs' -Recurse | ForEach-Object { Get-Content $_.FullName -Raw }) -join "`n"
$services = (Get-ChildItem (Join-Path $featureRoot 'Services') -Filter '*.cs' -Recurse | ForEach-Object { Get-Content $_.FullName -Raw }) -join "`n"
$all = $command + $form + $models + $services
Assert-Text $command 'class CmdParameterManager : IExternalCommand' 'public command'; Assert-Text $command 'Transaction(TransactionMode.Manual)' 'manual transaction'; Assert-Text $command 'ParameterManagerPlanner.BuildPlan' 'thin command planner'; Assert-Text $command 'ParameterManagerPreflightService.Validate' 'command preflight'; Assert-Text $command 'ParameterManagerExecutionService.Execute' 'command execution'
Assert-Text $form 'Parameter Manager 2.0' 'form title'; Assert-Text $form 'Preview' 'preview action'; Assert-Text $form 'Apply' 'apply action'; Assert-Text $form 'Refresh' 'refresh action'; Assert-Text $form 'Cancel' 'cancel action'; Assert-Text $form 'DataGridView' 'preview grid'; Assert-Text $form 'MinimumSize' 'DPI-safe form'; Assert-Text $form 'TableLayoutPanel' 'responsive layout'; Assert-Text $form 'No model writes occurred' 'preview write boundary'; Assert-Text $form 'CURRENT_SELECTION' 'selection scope'; Assert-Text $all 'CURRENT_VIEW' 'view scope'; Assert-Text $all 'SELECTED_CATEGORY_IN_VIEW' 'category scope'; Assert-Text $all 'WHOLE_PROJECT' 'explicit whole project scope'; Assert-Text $all 'INSTANCE' 'instance mode'; Assert-Text $all 'TYPE' 'type mode'; Assert-Text $form 'Search' 'search filter'; Assert-Text $form 'Family' 'family filter'; Assert-Text $form 'Type' 'type filter'; Assert-Text $form 'Select All' 'visible select all'; Assert-Text $form 'Reset to Rules' 'manual reset'; Assert-Text $form 'IsManualOverride' 'manual override flag'; Assert-Text $form 'CellEndEdit' 'typed manual edit'; Assert-Text $form 'Filter' 'filter predicate'
Assert-Text $models 'ParameterKey' 'neutral identity reuse'; Assert-Text $models 'ParameterValueSnapshot' 'neutral snapshot reuse'; Assert-Text $models 'ParameterManagerRequest' 'request'; Assert-Text $models 'ParameterManagerPlan' 'immutable plan model'; Assert-Text $models 'ParameterEditItem' 'edit item'; Assert-Text $models 'ParameterRule' 'rule model'; Assert-Text $models 'ParameterManagerOptions' 'options'; Assert-Text $models 'ParameterManagerResult' 'result model'; Assert-Text $models 'ParameterManagerPreflightResult' 'preflight result'; Assert-Text $models 'ElementScopeMode' 'scope enum'; Assert-Text $models 'ParameterScopeMode' 'parameter scope enum'; Assert-Text $models 'ParameterRuleType' 'rule enum'; Assert-Text $models 'ParameterManagerStatus' 'status enum'; Assert-Text $models 'TYPE_IMPACT_WARNING' 'type impact warning'; Assert-Text $models 'STALE_PARAMETER_PLAN' 'stale status'; Assert-Text $models 'UNSAFE_ELEMENT_REFERENCE' 'ElementId safety status'; Assert-Text $models 'GROUP_CONSTRAINED' 'group status'; Assert-Text $models 'WRITE_RESTRICTED' 'ownership status'; Assert-Text $models 'POST_VERIFY_FAILED' 'post verification status'; Assert-Text $models 'TYPE_MISSING' 'type missing status'; Assert-Text $models 'STORAGE_TYPE_UNSUPPORTED' 'storage status'; Assert-Text $models 'VALUE_PARSE_FAILED' 'parse status'
Assert-Text $services 'ParameterTransferService.CreateKey' 'ParameterTransfer key reuse'; Assert-Text $services 'ParameterTransferService.Snapshot' 'ParameterTransfer snapshot reuse'; Assert-Text $services 'ParameterTransferService.FindMatchingParameter' 'parameter re-resolution'; Assert-Text $services 'WhereElementIsNotElementType' 'instance collection'; Assert-Text $services 'CURRENT_SELECTION' 'explicit selection scope'; Assert-Text $services 'CURRENT_VIEW' 'active view scope'; Assert-Text $services 'SELECTED_CATEGORY_IN_VIEW' 'category filter scope'; Assert-Text $services 'WHOLE_PROJECT' 'whole project guard'; Assert-Text $services 'ParameterScopeMode.TYPE' 'type target mode'; Assert-Text $services 'DeduplicateTypes' 'type deduplication'; Assert-Text $services 'TypeImpactCount' 'type impact count'; Assert-Text $services 'CoverageCount' 'coverage catalog'; Assert-Text $services 'DistinctValues' 'distinct values'; Assert-Text $services 'DisplayName' 'display names'; Assert-Text $services 'IdentityDisplay' 'identity disambiguation'
foreach ($rule in @('SET_VALUE','PREFIX','SUFFIX','FIND_REPLACE','TRIM','UPPERCASE','LOWERCASE','TITLE_CASE','REMOVE_PREFIX','REMOVE_SUFFIX','SUBSTRING_START_LENGTH','SUBSTRING_REMOVE_START_LENGTH','REGEX_REPLACE','NUMERIC_INCREMENT','NUMERIC_ADD','NUMERIC_SUBTRACT','NUMERIC_MULTIPLY','NUMERIC_DIVIDE','CLEAR_VALUE')) { Assert-Text $all $rule "rule $rule" }
Assert-Text $services 'OnlyIfMissing' 'only-if-missing'; Assert-Text $services 'CaseSensitive' 'case policy'; Assert-Text $services 'TryCompileRegex' 'regex preflight'; Assert-Text $services 'INVALID_REGEX' 'invalid regex status'; Assert-Text $services 'RULE_NOT_APPLICABLE' 'rule applicability'; Assert-Text $services 'INVALID_RULE_ARGUMENT' 'rule argument validation'; Assert-Text $services 'StartIndex' 'substring start'; Assert-Text $services 'Length' 'substring length'; Assert-Text $services 'TextInfo.ToTitleCase' 'culture title case'; Assert-Text $services 'NumericStart' 'numbering start'; Assert-Text $services 'NumericStep' 'numbering step'; Assert-Text $services 'Padding' 'numbering padding'; Assert-Text $services 'OrderBy(i => i.ElementId.IntegerValue)' 'deterministic ElementId ordering'
Assert-Text $services 'StorageType.String' 'string parser'; Assert-Text $services 'StorageType.Integer' 'integer parser'; Assert-Text $services 'StorageType.Double' 'double parser'; Assert-Text $services 'StorageType.ElementId' 'ElementId read-only path'; Assert-Text $services 'UnitUtils.ConvertToInternalUnits' 'Revit unit conversion'; Assert-Text $services 'UnitTypeId.Millimeters' 'millimeter input'; Assert-Text $services 'Yes/No' 'boolean parser'; Assert-Text $services 'Clear' 'typed clear'; Assert-Text $services 'UNSAFE_ELEMENT_REFERENCE' 'ElementId writes blocked'; Assert-Text $services 'NUMERIC_SUBTRACT' 'numeric subtract'; Assert-Text $services 'NUMERIC_DIVIDE' 'numeric divide'; Assert-Text $services 'STORAGE_TYPE_UNSUPPORTED' 'storage preflight'; Assert-Text $services 'DATA_TYPE_UNSUPPORTED' 'data type preflight'; Assert-Text $services 'INVALID_RULE' 'invalid rule status'
Assert-Text $services 'IsProtected' 'protected parameter policy'; Assert-Text $services 'SHEET_NUMBER' 'sheet identity protection'; Assert-Text $services 'SHEET_NAME' 'sheet name protection'; Assert-Text $services 'revision' 'revision protection'; Assert-Text $services 'AllowProtectedParameters' 'explicit protected override'; Assert-Text $services 'IsReadOnly' 'read-only preflight'; Assert-Text $services 'GroupId' 'group safety'; Assert-Text $all 'WRITE_RESTRICTED' 'write restriction classification'
Assert-Text $services 'Fingerprint' 'plan fingerprint'; Assert-Text $services 'DocumentIdentity.From(doc).StableKey' 'document identity fingerprint'; Assert-Text $services 'BuildCurrentFingerprint' 'stale fingerprint validation'; Assert-Text $services 'STALE_PARAMETER_PLAN' 'stale plan guard'; Assert-Text $services 'PreviewOnly' 'preview option'; Assert-Text $services 'NO_CHANGE' 'no-change action'; Assert-Text $services 'using (var group = new TransactionGroup' 'outer transaction group'; Assert-Text $services 'using (var tx = new Transaction' 'per-item transaction isolation'; Assert-Text $services 'AllOrNothing' 'strict mode'; Assert-Text $services 'ALL_OR_NOTHING_ROLLED_BACK' 'strict rollback'; Assert-Text $services 'Verify' 'post-write verification'; Assert-Text $services 'VerifyUnselectedUnchanged' 'unselected preservation'; Assert-Text $services 'TryCompileRegex' 'compile regex before preview'
Assert-NotText $services 'ParameterManagerParameterKey' 'no duplicate identity model'; Assert-NotText $services 'ParameterManagerValueSnapshot' 'no duplicate snapshot model'; Assert-NotText $services 'SetValueString' 'no universal SetValueString'; Assert-NotText $services 'catch { }' 'no silent catches'
$fixture = Get-Content (Join-Path $root 'KhimTools\Tools\KhimGen\RuntimeQa\Fixtures\ParameterManagerRuntimeFixture.cs') -Raw; Assert-Text $fixture 'ParameterManagerRuntimeFixture' 'runtime fixture'; Assert-Text $fixture 'ParameterDiscoveryService.Discover' 'fixture discovery'; Assert-Text $fixture 'ParameterManagerPlanner.BuildPlan' 'fixture planner'; Assert-Text $fixture 'ParameterManagerPreflightService.Validate' 'fixture preflight'; Assert-Text $fixture 'ParameterManagerExecutionService.Execute' 'fixture execution'; Assert-Text $fixture 'ParameterManagerVerificationService' 'fixture verification'; Assert-Text $fixture 'PM35_NUMERIC' 'numeric fixture path'; Assert-Text $fixture 'PM35_READ_ONLY' 'read-only fixture path'; Assert-Text $fixture 'PM35_TYPE_IMPACT' 'type impact fixture path'; Assert-Text $fixture 'PM35_UNSELECTED' 'unselected fixture path'; Assert-Text $fixture 'Block(' 'blocked prerequisite'; Assert-Text $fixture 'TransactionGroup' 'rollback boundary'
$registry = Get-Content (Join-Path $root 'KhimTools\Tools\KhimGen\RuntimeQa\Core\RuntimeQaRegistry.cs') -Raw; Assert-Text $registry 'ParameterManagerRuntimeFixture' 'fixture registry'; $ribbon = Get-Content (Join-Path $root 'KhimTools\Core\RibbonBuilder.cs') -Raw; Assert-Text $ribbon 'KhimTools.ParameterManager.Commands.CmdParameterManager' 'ribbon command registration'
foreach ($file in (Get-ChildItem -LiteralPath $featureRoot -Recurse -Filter '*.cs')) { $text = Get-Content -LiteralPath $file.FullName -Raw; if ($text -match '(?ms)catch\s*\{\s*\}') { throw "FAIL: silent catch in $($file.FullName)" }; $checks++ }
Write-Output "PASS: $checks Parameter Manager Stage 3.5 static checks. No Revit model operation executed."
