$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$featureRoot = Join-Path $root 'KhimTools\Tools\KhimGen\DimensionTools'
$checks = 0
function Read-Feature([string]$relative) { $path = Join-Path $featureRoot $relative; if (-not (Test-Path -LiteralPath $path)) { throw "FAIL: missing Dimension Tools file $relative" }; return Get-Content -LiteralPath $path -Raw }
function Read-Repo([string]$relative) { $path = Join-Path $root $relative; if (-not (Test-Path -LiteralPath $path)) { throw "FAIL: missing repository file $relative" }; return Get-Content -LiteralPath $path -Raw }
function Assert-Text([string]$text, [string]$needle, [string]$label) { if ($text.IndexOf($needle, [StringComparison]::Ordinal) -lt 0) { throw "FAIL: $label" }; $script:checks++ }
function Assert-NotText([string]$text, [string]$needle, [string]$label) { if ($text.IndexOf($needle, [StringComparison]::Ordinal) -ge 0) { throw "FAIL: $label" }; $script:checks++ }
$all = (Get-ChildItem -LiteralPath $featureRoot -Recurse -Filter '*.cs' | ForEach-Object { Get-Content $_.FullName -Raw }) -join "`n"
$core = (Get-ChildItem (Join-Path $featureRoot 'Core') -Recurse -Filter '*.cs' | ForEach-Object { Get-Content $_.FullName -Raw }) -join "`n"
$models = (Get-ChildItem (Join-Path $featureRoot 'Models') -Recurse -Filter '*.cs' | ForEach-Object { Get-Content $_.FullName -Raw }) -join "`n"
$services = (Get-ChildItem (Join-Path $featureRoot 'Services') -Recurse -Filter '*.cs' | ForEach-Object { Get-Content $_.FullName -Raw }) -join "`n"
$command = Read-Feature 'Commands\CmdDimensionTools.cs'; $form = Read-Feature 'Forms\DimensionToolsForm.cs'
foreach ($file in @('Core\DimensionApiAdapter.cs','Core\DimensionContext.cs','Core\DimensionPlan.cs','Core\DimensionPlanBuilder.cs','Core\DimensionPreflightService.cs','Core\DimensionExecutionService.cs','Core\DimensionVerificationService.cs','Core\DimensionReferenceService.cs','Core\DimensionGeometryService.cs','Core\DimensionStyleService.cs','Core\ViewPlane.cs','Models\DimensionOperation.cs','Models\DimensionReferenceInfo.cs','Models\DimensionChainPlan.cs','Models\DimensionPlanItem.cs','Models\DimensionStatus.cs','Models\DimensionResult.cs','Models\DimensionOptions.cs','Services\GridDimensionService.cs','Services\ColumnDimensionService.cs','Services\BeamDimensionService.cs','Services\FoundationDimensionService.cs','Services\OpeningDimensionService.cs','Services\ElevationDimensionService.cs','Services\QuickDimensionService.cs','Services\GeneralDimensionService.cs','Services\CutDimensionService.cs','Services\JoinDimensionService.cs','Services\ZeroDimensionService.cs','Services\DimensionTextService.cs')) { Assert-Text $all ([IO.Path]::GetFileNameWithoutExtension($file)) "architecture $file" }
Assert-Text $command 'class CmdDimensionTools : IExternalCommand' 'public command'; Assert-Text $command 'Transaction(TransactionMode.Manual)' 'manual transaction'; Assert-Text $command 'DimensionToolsForm' 'single manager form'; Assert-Text $command 'ViewPlane.IsSupportedView' 'view preflight'; Assert-Text $form 'Dimension Tools 2.0' 'form title'; Assert-Text $form 'AUTO DIM' 'auto tab'; Assert-Text $form 'EDIT DIM' 'edit tab'; Assert-Text $form 'Preview' 'preview action'; Assert-Text $form 'Apply' 'apply action'; Assert-Text $form 'Refresh' 'refresh action'; Assert-Text $form 'Close' 'close action'; Assert-Text $form 'MinimumSize' 'DPI-safe form'; Assert-Text $form 'TableLayoutPanel' 'responsive layout'; Assert-Text $form 'No model writes occurred' 'preview write boundary'
foreach ($token in @('GRID','COLUMN','BEAM','FOUNDATION','OPENING','ELEVATION','SPOT_ELEVATION','QUICK','GENERAL','CUT','JOIN','REMOVE_ZERO','MOVE_TEXT')) { Assert-Text $models $token "operation $token" }
foreach ($token in @('READY','NO_CHANGE','INVALID_SELECTION','UNSUPPORTED_VIEW_TYPE','UNSUPPORTED_ELEMENT','REFERENCE_NOT_FOUND','REFERENCE_INVALID','REFERENCE_NOT_PARALLEL','REFERENCE_NOT_COPLANAR','REFERENCE_DUPLICATE','INSUFFICIENT_REFERENCES','INVALID_DIMENSION_AXIS','INVALID_DIMENSION_LINE','DIMENSION_TYPE_MISSING','DIMENSION_TYPE_INVALID','STALE_REFERENCE','STALE_DIMENSION_PLAN','CREATED','UPDATED','PARTIAL','SKIPPED','FAILED','POST_VERIFY_FAILED','CENTER_REFERENCE_UNAVAILABLE','CYLINDRICAL_FACE_UNSUPPORTED','CURVED_GRID_UNSUPPORTED','CURVED_BEAM_UNSUPPORTED','FOUNDATION_TYPE_UNSUPPORTED','AMBIGUOUS_REFERENCE_STRATEGY','DIMENSIONS_INCOMPATIBLE','EQUALITY_CONSTRAINT_RISK','CONSTRAINT_DIMENSION_UNSUPPORTED','MANUAL_OVERRIDE_RISK','TEXT_LAYOUT_NOT_FULLY_PRESERVED')) { Assert-Text $models $token "status $token" }
foreach ($token in @('ViewId','Operation','References','DimensionLine','DimensionTypeId','ExpectedSegments','Warnings','Fingerprint','DimensionPlan','CanExecute','BuildFingerprint','STALE_DIMENSION_PLAN','DimensionPreflightService','DimensionExecutionService','DimensionVerificationService','TransactionGroup','SubTransaction','Regenerate','ReferenceArray','NewDimension','NewSpotElevation','DimensionType','NumberOfSegments','Segments','DimensionSegment','Value','TextPosition','AreSegmentsEqual','ComputeReferences','DetailLevel','GetGeometryObjectFromReference','GetReferences','GetReferenceByName','ConvertToStableRepresentation','ParseFromStableRepresentation','ResolveStableReference','CaptureSnapshot','AreSegmentsEqual','ValueOverride','Prefix','Suffix','Above','Below','LeaderEndPosition')) { Assert-Text $core $token "core API/pipeline $token" }
foreach ($token in @('Origin','RightDirection','UpDirection','ViewDirection','ToView','FromView','Project','IsSupportedView','AngularToleranceRadians','SortByProjectedPosition','DotProduct','CrossProduct','UnitUtils.ConvertToInternalUnits','UnitTypeId.Millimeters')) { Assert-Text $core $token "view plane/geometry $token" }
foreach ($token in @('NewDimension','ReferenceArray','Grid','GridDimensionService','CURVED_GRID_UNSUPPORTED','FromGrid','SortGridChain')) { Assert-Text $services $token "grid $token" }
foreach ($token in @('StructuralColumns','CENTERLINE','FACE_TO_FACE','GRID_TO_COLUMN','COLUMN_FACE','FamilyInstance','Transform','Cylindrical','CENTER_REFERENCE_UNAVAILABLE')) { Assert-Text $services $token "column $token" }
foreach ($token in @('StructuralFraming','LENGTH','END_TO_END','GRID_TO_GRID','FACE_CHAIN','LocationCurve','CURVED_BEAM_UNSUPPORTED','PROJECTED_VIEW_DIMENSION')) { Assert-Text $services $token "beam $token" }
foreach ($token in @('StructuralFoundation','WIDTH','LENGTH','GRID_OFFSET','FOUNDATION_TYPE_UNSUPPORTED','FOUNDATION_FACE')) { Assert-Text $services $token "foundation $token" }
foreach ($token in @('Opening','Doors','Windows','OPENING_EDGE','GetReferences','GetReferenceByName','Host')) { Assert-Text $services $token "opening $token" }
foreach ($token in @('Level','LEVEL','NewSpotElevation','SPOT_ELEVATION','Reference','origin','bend','end','refPoint')) { Assert-Text $services $token "elevation $token" }
foreach ($token in @('AMBIGUOUS_REFERENCE_STRATEGY','Center','NEAR_FACE','FAR_FACE','HORIZONTAL_IN_VIEW','VERTICAL_IN_VIEW','Pick Dimension Line')) { Assert-Text $services $token "quick/general $token" }
foreach ($token in @('CUT','JOIN','REMOVE_ZERO','DimensionRebuildService','CreateReplacement','Replacement','verify','Delete','INSUFFICIENT_REFERENCES','DIMENSIONS_INCOMPATIBLE','zero','tolerance')) { Assert-Text $services $token "edit operation $token" }
foreach ($token in @('ViewPlane','RightDirection','UpDirection','MoveText','TextPosition','DimensionSegment','view-local')) { Assert-Text $services $token "text move $token" }
$registry = Read-Repo 'KhimTools\Tools\KhimGen\RuntimeQa\Core\RuntimeQaRegistry.cs'; $fixture = Read-Repo 'KhimTools\Tools\KhimGen\RuntimeQa\Fixtures\DimensionToolsRuntimeFixture.cs'; $ribbon = Read-Repo 'KhimTools\Core\RibbonBuilder.cs'; $gridGenerator = Read-Repo 'KhimTools\Tools\KhimGen\GridLevel\Services\GridGeneratorService.cs'; $modify = (Get-ChildItem (Join-Path $root 'KhimTools\Tools\KhimGen\ModifyObjects') -Recurse -Filter '*.cs' | ForEach-Object { Get-Content $_.FullName -Raw }) -join "`n"; $rebar = Read-Repo 'KhimTools\Tools\KhimStructural\RebarTool\Core\ColumnRebarDrawingGenerator.cs'
Assert-Text $registry 'DimensionToolsRuntimeFixture' 'runtime fixture registration'; Assert-Text $fixture 'DIMENSION_TOOLS_STAGE37' 'runtime fixture id'; Assert-Text $fixture 'TransactionGroup rollback' 'runtime rollback'; Assert-Text $fixture 'Block(' 'runtime blocked prerequisites'; Assert-Text $ribbon 'KhimTools.DimensionTools.Commands.CmdDimensionTools' 'ribbon command'; Assert-Text $gridGenerator 'NewDimension' 'grid regression source retained'; Assert-Text $modify 'ModifyObject' 'Modify Objects regression retained'; Assert-Text $rebar 'NewDimension' 'Rebar dimension source retained'
Assert-NotText $all 'SwallowWarningsPreprocessor' 'dimension module does not swallow warnings'; Assert-NotText $all 'SetValue' 'no dimension value editing'; Assert-NotText $all 'ValueString' 'no ValueString reconstruction'; foreach ($file in (Get-ChildItem -LiteralPath $featureRoot -Recurse -Filter '*.cs')) { $text = Get-Content -LiteralPath $file.FullName -Raw; if ($text -match '(?ms)catch\s*\{\s*\}') { throw "FAIL: silent catch in $($file.FullName)" }; $checks++ }
Write-Output "PASS: $checks Dimension Tools Stage 3.7 static checks. No Revit model operation executed."
