[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$base = Join-Path $repoRoot 'KhimTools\Tools\KhimStructural\RebarTool'
$checks = [System.Collections.Generic.List[object]]::new()

function Add-Check([string]$Name, [bool]$Pass, [string]$Evidence) {
    $script:checks.Add([pscustomobject]@{ Name = $Name; Pass = $Pass; Evidence = $Evidence })
}

$required = @(
    'Core\BeamRebarGenerator.cs',
    'Core\RectangularColumnRebarGenerator.cs',
    'Core\CircularColumnRebarGenerator.cs',
    'Core\SlabRebarGenerator.cs',
    'Core\FoundationRebarGenerator.cs',
    'Core\RebarGenerationReport.cs',
    'Core\RebarGenerationFailurePreprocessor.cs',
    'Core\RebarShapeCreationHelper.cs',
    'Core\RebarCoverHelper.cs',
    'Core\RebarHookHelper.cs',
    'Core\RebarLapSpliceHelper.cs',
    'Forms\BeamReinforcementForm.cs',
    'Forms\RectangularColumnReinforcementForm.cs',
    'Forms\CircularColumnReinforcementForm.cs',
    'Forms\SlabReinforcementForm.cs',
    'Forms\FoundationReinforcementForm.cs'
)
foreach ($relative in $required) {
    $path = Join-Path $base $relative
    Add-Check "production-source:$relative" (Test-Path -LiteralPath $path) $path
}

$runtimePath = Join-Path $repoRoot 'KhimTools\Tools\KhimGen\RuntimeQa\Fixtures\RebarRuntimeFixtures.cs'
$runtimeText = if (Test-Path -LiteralPath $runtimePath) { Get-Content -Raw $runtimePath } else { '' }
foreach ($fixture in @('RC-STATION', 'RC-FULL', 'CC', 'BR', 'SR', 'FR', 'RC-PREVIEW', 'BR-PREVIEW-RECT', 'BR-PREVIEW-ROTATED', 'SR-PREVIEW-RECT', 'SR-PREVIEW-OPENING', 'CC-PREVIEW')) {
    Add-Check "runtime-fixture:$fixture" ($runtimeText.Contains('"' + $fixture + '"')) $runtimePath
}

$columnText = Get-Content -Raw (Join-Path $base 'Forms\RectangularColumnReinforcementForm.cs')
Add-Check 'rectangular-column-2d-form-preview' ($columnText.Contains('PreviewPanel_Paint')) 'Form paints a responsive 2D schematic.'
$columnPaintBody = [regex]::Match($columnText, '(?s)private void PreviewPanel_Paint\(.*?(?=\r?\n        private void ApplyLanguage\()').Value
Add-Check 'rectangular-column-paint-uses-detached-host-summary' ($columnPaintBody.Contains('_previewWidthMm') -and $columnPaintBody.Contains('_previewHostError') -and $columnPaintBody -notmatch 'GetRectangularProfile|LookupParameter|_doc\.GetElement|UnitUtils\.') 'Paint reads the cached host summary only; Revit geometry and parameter access occur on selection changes, and unsupported hosts are shown as unavailable.'
Add-Check 'rectangular-column-schematic-is-disclosed-as-not-solved' ($columnText.Contains('ColumnSchematicDisclosure') -and $columnPaintBody.Contains('ColumnSchematicDisclosure') -and $columnPaintBody.Contains('g.DrawString(secTitle')) 'The configuration diagram is visibly labeled as not-solved geometry in the active UI language; exact reinforcement geometry is only represented by the accepted solver preview.'
Add-Check 'rectangular-column-create-gated-by-current-preview' ($columnText.Contains('_previewLifecycle.State == PreviewLifecycleState.Valid && _lastPreview != null') -and $columnText.Contains('UpdatePreviewStateUi();') -and $columnText.Contains('_formGuard?.ValidateNow();')) 'Create stays disabled until a solver-backed preview is accepted and current.'
Add-Check 'rectangular-column-legacy-unmapped-settings-disabled' ($columnText.Contains('_grpHook.Enabled = false;') -and $columnText.Contains('_grpBendCut.Enabled = false;') -and $columnText.Contains('_grpTopRoof.Enabled = false;') -and $columnText.Contains('_grpSplicePos.Enabled = false;') -and $columnText.Contains('_grpAssignInfo.Enabled = false;') -and $columnText.Contains('_grpSlabBeam.Enabled = false;') -and $columnText.Contains('(not applied)')) 'Legacy hook, bend, top-roof, splice-base, metadata, and beam-height controls are disabled and disclosed because they are not consumed by the production column input.'
$previewServicePath = Join-Path $base 'Core\RebarPreviewService.cs'
$previewService = if (Test-Path -LiteralPath $previewServicePath) { Get-Content -Raw $previewServicePath } else { '' }
$previewFormPath = Join-Path $base 'Forms\RebarSolverPreviewForm.cs'
$previewForm = if (Test-Path -LiteralPath $previewFormPath) { Get-Content -Raw $previewFormPath } else { '' }
$registryPath = Join-Path $repoRoot 'KhimTools\Tools\KhimGen\RuntimeQa\Core\RuntimeQaRegistry.cs'
$registryText = if (Test-Path -LiteralPath $registryPath) { Get-Content -Raw $registryPath } else { '' }
$coverHelper = Get-Content -Raw (Join-Path $base 'Core\RebarCoverHelper.cs')
$coverHelperSource = $coverHelper
$circularGeometry = Get-Content -Raw (Join-Path $base 'Core\CircularColumnGeometryHelper.cs')
$circularGenerator = Get-Content -Raw (Join-Path $base 'Core\CircularColumnRebarGenerator.cs')
$rectangularGenerator = Get-Content -Raw (Join-Path $base 'Core\RectangularColumnRebarGenerator.cs')
$rectangularGeometry = Get-Content -Raw (Join-Path $base 'Core\RectangularColumnGeometryHelper.cs')
$beamGeometry = Get-Content -Raw (Join-Path $base 'Core\BeamGeometryHelper.cs')
Add-Check 'common-detached-preview-pipeline' ($previewService.Contains('class RebarPreviewService') -and $previewService.Contains('class RebarPreviewSnapshot')) $previewServicePath
Add-Check 'rebar-cover-resolves-requested-host-face' ($coverHelper.Contains('private static double GetFaceCover(Element host, RebarFace face)') -and $coverHelper.Contains('BuiltInParameter.CLEAR_COVER_TOP') -and $coverHelper.Contains('BuiltInParameter.CLEAR_COVER_BOTTOM') -and $coverHelper.Contains('BuiltInParameter.CLEAR_COVER_EXTERIOR') -and $coverHelper.Contains('GetCommonCoverType()')) 'Cover helpers prefer each requested face parameter and use common-cover fallback only when a face parameter is unavailable.'
Add-Check 'project-cover-creation-never-falls-back-to-unrelated-type' ($coverHelperSource.Contains('matchTolerance = ToFeet(0.1)') -and $coverHelperSource.Contains('requested distance of ') -and $coverHelperSource.Contains('hostData.SetCommonCoverType(coverType)') -and $coverHelperSource.Contains('Could not apply the requested Rebar cover type to host element') -and $coverHelperSource -notmatch 'FirstOrDefault\(\);\s*\}') 'Project cover setup resolves a type within 0.1 mm of the requested distance or fails visibly; assignment errors identify the host and propagate so the owning transaction can roll back.'
Add-Check 'rollback-only-solver-capture' ($previewService.Contains('transaction.RollBack()') -and $previewService.Contains('WorkflowFingerprint') -and $previewService.Contains('RolledBack')) 'Capture rolls back and verifies pre/post document fingerprints.'
Add-Check 'solver-derived-centerline-geometry' ($previewService.Contains('GetCenterlineCurves') -and $previewService.Contains('Tessellate')) 'Detached path coordinates are captured from Revit-solved centerlines.'
Add-Check 'solver-preview-inspection-controls' ($previewForm.Contains('"ISO"') -and $previewForm.Contains('"TOP"') -and $previewForm.Contains('"FRONT"') -and $previewForm.Contains('"RIGHT"') -and $previewForm.Contains('"FIT"') -and $previewForm.Contains('"FIT ALL"') -and $previewForm.Contains('private void FitAll()') -and $previewForm.Contains('_componentSelector.SelectedIndex = 0') -and $previewForm.Contains('_roleSelector.SelectedIndex = 0') -and $previewForm.Contains('Canvas_MouseWheel') -and $previewForm.Contains('Canvas_MouseMove') -and $previewForm.Contains('0.82f') -and $previewForm.Contains('Filter solver preview by host') -and $previewForm.Contains('GetVisibleComponents()')) 'Detached Rebar solver viewer provides four engineering projections, per-host filtering, 82% fit, bounded wheel zoom, pan, Fit and Fit All to reset host/role scope.'
Add-Check 'solver-preview-colors-canonical-reinforcement-roles' ($previewForm.Contains('private static Color RoleColor(string role)') -and $previewForm.Contains('case "longitudinal"') -and $previewForm.Contains('case "outer-tie"') -and $previewForm.Contains('case "bottom-x"') -and $previewForm.Contains('case "perimeter-u"') -and $previewForm.Contains('new Pen(RoleColor(role), 2f)') -and $previewForm.Contains('rolePens[rolePath.Role ?? string.Empty]')) 'Detached solver centerlines use cached role-semantic pens for primary bars, ties, slab layers and foundation perimeter bars; role filtering still subdues inactive paths.'
$referenceViews = Get-Content -Raw (Join-Path $base 'Forms\RebarReferenceViews.cs')
$localizedRebarSurfaces = @(
    (Get-Content -Encoding UTF8 -Raw (Join-Path $base 'Forms\RectangularColumnReinforcementForm.cs')),
    (Get-Content -Encoding UTF8 -Raw (Join-Path $base 'Forms\BeamReinforcementForm.cs')),
    (Get-Content -Encoding UTF8 -Raw (Join-Path $base 'Forms\CircularColumnReinforcementForm.cs')),
    (Get-Content -Encoding UTF8 -Raw (Join-Path $base 'Forms\SlabReinforcementForm.cs')),
    (Get-Content -Encoding UTF8 -Raw (Join-Path $base 'Forms\FoundationReinforcementForm.cs')),
    (Get-Content -Encoding UTF8 -Raw (Join-Path $base 'Forms\RebarReferenceViews.cs'))
) -join "`n"
Add-Check 'rebar-user-facing-surfaces-vietnamese-encoding' ($localizedRebarSurfaces -cnotmatch '(?:\u00C3[\u00A0-\u00BF]|\u00E1[\u00BA\u00BB]|\u00C4[\u00A0-\u00BF]|\u00E2\u20AC\u00A2|\uFFFD)') 'UTF-8 is decoded explicitly; Beam, column, circular-column, slab, foundation, and reference-view source contain no common mojibake byte sequences or replacement characters.'
Add-Check 'stable-input-fingerprints' ($previewService.Contains('VersionGuid') -and $previewService.Contains('BarsAlongB') -and $previewService.Contains('TieLayout') -and $previewService.Contains('AdjacentColumnAbove.VersionGuid') -and $previewService.Contains('AdjacentColumnBelow.VersionGuid')) 'Fingerprint includes host/type/adjacent-host versions and generation settings.'
Add-Check 'preview-ui-wired' ($columnText.Contains('RebarPreviewService.Capture') -and $columnText.Contains('new RebarSolverPreviewForm') -and $previewForm.Contains('RebarPreviewSnapshot') -and $previewForm.Contains('DrawLines')) 'Rectangular-column UI renders detached solver paths in a disposable preview form.'
Add-Check 'precommit-preview-parity' ($columnText.Contains('RebarPreviewService.Matches') -and $columnText.Contains('_lastPreview')) 'Generation rejects missing/stale preview and compares solved geometry before commit.'
Add-Check 'preview-runtime-fixture-registered' ($registryText.Contains('new RectangularColumnPreviewRuntimeFixture()')) $registryPath

$beamText = Get-Content -Raw (Join-Path $base 'Forms\BeamReinforcementForm.cs')
$slabText = Get-Content -Raw (Join-Path $base 'Forms\SlabReinforcementForm.cs')
$slabEdgeText = Get-Content -Raw (Join-Path $base 'Forms\SlabEdgePickerForm.cs')
$slabGeometry = Get-Content -Raw (Join-Path $base 'Core\SlabGeometryHelper.cs')
$slabHostScenarios = Get-Content -Raw (Join-Path $repoRoot 'Tools\RebarPreviewHostScenarios.md')
$beamGenerator = [System.IO.File]::ReadAllText((Join-Path $base 'Core\BeamRebarGenerator.cs'), [System.Text.Encoding]::UTF8)
Add-Check 'beam-generator-vietnamese-encoding' ($beamGenerator -cnotmatch '(?:\u00C3.|\u00E1[\u00BA\u00BB]|\u00C4.|\u00E2(?:\u20AC|\u201C|\u201D|\u0080|\u0094)|\uFFFD)') 'Beam generator comments and diagnostics contain no common UTF-8 mojibake signatures or replacement characters.'
$slabGenerator = Get-Content -Raw (Join-Path $base 'Core\SlabRebarGenerator.cs')
$foundationText = Get-Content -Raw (Join-Path $base 'Forms\FoundationReinforcementForm.cs')
$foundationRoleNavigation = $foundationText.Contains('Foundation role-oriented settings') -and $foundationText.Contains('AddRoleNavigation(roleNavigation') -and $foundationText.Contains('UpdateRoleNavigation();') -and $foundationText.Contains('ItemSize = new Size(0, 1)')
Add-Check 'foundation-role-navigation-replaces-duplicate-tabs' $foundationRoleNavigation 'Foundation settings use a compact role navigator with the duplicate tab strip hidden.'
Add-Check 'foundation-language-selector-applies-global-language' ($foundationText.Contains('_cmbLanguage.SelectedIndexChanged') -and $foundationText.Contains('LanguageManager.CurrentLanguage = _cmbLanguage.SelectedIndex == 1') -and $foundationText.Contains('private void ApplyLanguage()') -and $foundationText.Contains('vietnameseToEnglish') -and $foundationText.Contains('RebarReferenceViews.CreatePage(RebarReferenceKind.Foundation)')) 'Foundation language selection updates the shared setting, translates form controls in both directions and rebuilds the localized reference page.'
Add-Check 'slab-language-selector-applies-global-language' ($slabText.Contains('_cmbLanguage.SelectedIndexChanged') -and $slabText.Contains('LanguageManager.CurrentLanguage = _cmbLanguage.SelectedIndex == 1') -and $slabText.Contains('private void ApplyLanguage()') -and $slabText.Contains('SLAB ENGINEERING PREVIEW') -and $slabText.Contains('Preview not generated') -and $slabText.Contains('RebarReferenceViews.CreatePage(RebarReferenceKind.Slab)')) 'Slab language selection updates the shared setting, localizes the workflow and dynamic preview status, and rebuilds the localized reference page.'
$validationGuardText = Get-Content -Raw (Join-Path $base 'Forms\RebarFormGuard.cs')
Add-Check 'rebar-validation-status-and-errors-follow-selected-language' ($validationGuardText.Contains('public void ApplyLanguage()') -and $validationGuardText.Contains('Validate Inputs') -and $validationGuardText.Contains('Inputs are valid.') -and $validationGuardText.Contains('internal static string LocalizeMessage') -and $validationGuardText.Contains('Select at least one foundation.') -and $slabText.Contains('_formGuard?.ApplyLanguage();') -and $foundationText.Contains('_formGuard?.ApplyLanguage();') -and $columnText.Contains('_formGuard?.ApplyLanguage();')) 'Shared validation-strip labels, status summaries and error messages follow Vietnamese/English selection across Slab, Foundation and rectangular Column forms.'
$configurationPageText = Get-Content -Raw (Join-Path $base 'Forms\RebarConfigurationPage.cs')
Add-Check 'rebar-configuration-page-localizes-all-shared-controls' ($configurationPageText.Contains('internal static void ApplyLanguage(TabPage page)') -and $configurationPageText.Contains('Project default') -and $configurationPageText.Contains('Per element type') -and $configurationPageText.Contains('Override') -and $configurationPageText.Contains('Dowel anchorage leg (mm)') -and $configurationPageText.Contains('Bar-length rounding step (mm)') -and $configurationPageText.Contains('Save & Apply') -and $foundationText.Contains('RebarConfigurationPage.ApplyLanguage(') -and $columnText.Contains('RebarConfigurationPage.ApplyLanguage(') -and $slabText.Contains('RebarConfigurationPage.ApplyLanguage(')) 'Shared Rebar project-configuration UI localizes its selector, headers, parameter labels, source values and actions for Column, Slab and Foundation.'
$foundationGenerator = Get-Content -Raw (Join-Path $base 'Core\FoundationRebarGenerator.cs')
$foundationGeometry = Get-Content -Raw (Join-Path $base 'Core\FoundationGeometryHelper.cs')
$foundationSettings = Get-Content -Raw (Join-Path $base 'Models\FoundationRebarSettings.cs')
$foundationRuntime = Get-Content -Raw $runtimePath
$circularText = Get-Content -Raw (Join-Path $base 'Forms\CircularColumnReinforcementForm.cs')
Add-Check 'column-solver-preview-retains-role-identity' ($rectangularGenerator.Contains('RecordRoles(mainBars, "longitudinal"') -and $rectangularGenerator.Contains('GetTieRole(tie, stationBars, input)') -and $rectangularGenerator.Contains('"outer-tie"') -and $rectangularGenerator.Contains('"inner-tie-left"') -and $rectangularGenerator.Contains('"inner-tie-right"') -and $rectangularGenerator.Contains('"diamond-tie"') -and $rectangularGenerator.Contains('"cross-tie"') -and $circularGenerator.Contains('RecordRoles(mainBars, "longitudinal"') -and $circularGenerator.Contains('RecordRoles(ties, "tie"') -and $columnText.Contains('generator.Generate(input, report, roleByBarId)') -and $circularText.Contains('generator.Generate(input, report, roleByBarId)') -and $previewForm.Contains('Highlight solver preview by reinforcement role') -and $previewForm.Contains('Text = "Highlight:"') -and $previewForm.Contains('selectedRole == null || rolePath.Role == selectedRole')) 'Rectangular and circular column modal previews retain roles assigned by the production generator and highlight only the selected solver path group.'
$circularRuntime = $runtimeText
Add-Check 'beam-solver-preview-calls-production-generator' ($beamText.Contains('RebarPreviewService.Capture') -and $beamText.Contains('generator.Generate(input, null, roleByBarId)') -and $beamText.Contains('RebarPreviewService.Matches')) 'Beam preview and pre-commit verification invoke BeamRebarGenerator.'
Add-Check 'beam-ui-reference-controls-disabled-and-hangers-wired' ($beamText.Contains('DisableUnmappedLegacyInputs();') -and $beamText.Contains('_cmbMainTopStartPoint') -and $beamText.Contains('_txtMainTopAnchorLeft') -and $beamText.Contains('_cmbAddTopLayer') -and $beamText.Contains('_txtAddTopLeftLen') -and $beamText.Contains('_cmbStirrupSpan') -and $beamText.Contains('_cmbAntiBulgeOffset') -and $beamText.Contains('HangerStirrupQty = (int)_numHangerStirrupQty.Value') -and $beamText.Contains('HangerStirrupSpacingMm = (double)_numHangerStirrupSpacing.Value') -and $beamGenerator.Contains('if (qty == 0) return hoops;')) 'Beam-only schematic fields are non-editable; actual hanger count and spacing are explicit and feed the canonical generator.'
Add-Check 'beam-solver-preview-retains-generator-role-identity' ($beamGenerator.Contains('RecordRoles(topContinuous, "top-continuous"') -and $beamGenerator.Contains('RecordRoles(bottomContinuous, "bottom-continuous"') -and $beamGenerator.Contains('RecordRoles(bars, "top-left-extra"') -and $beamGenerator.Contains('RecordRoles(bars, "top-right-extra"') -and $beamGenerator.Contains('RecordRoles(bars, "bottom-mid-extra"') -and $beamGenerator.Contains('RecordRoles(bars, "side-bars"') -and $beamGenerator.Contains('RecordRoles(stirrups, "stirrup"') -and $beamGenerator.Contains('RecordRoles(hangerStirrups, "hanger-stirrup"') -and $beamText.Contains('roleByBarId.TryGetValue') -and $previewForm.Contains('"stirrup"')) 'Beam detached solver preview roles are assigned to actual production generator batches and exposed to the shared role filter.'
Add-Check 'beam-static-schematic-is-not-mislabeled-as-solved-preview' ($beamText.Contains('ILLUSTRATIVE_ONLY_NOT_SOLVED_GEOMETRY') -and $beamText.Contains('BeamSchematicDisclosure') -and $beamText.Contains('DrawString(BeamSchematicDisclosure')) 'The hard-coded beam elevation sketch is visibly identified as illustrative; the solver-backed dialog remains the only geometry preview claim.'
Add-Check 'beam-create-gated-by-visible-current-preview-state' ($beamText.Contains('Beam solver preview state') -and $beamText.Contains('HasCurrentAcceptedPreview') -and $beamText.Contains('AttachPreviewInvalidationHandlers(this)') -and $beamText.Contains('Inputs changed')) 'Beam exposes preview lifecycle state, immediately stales on input edits and disables Create until the current solve is accepted.'
Add-Check 'beam-continuous-bar-quantity-is-not-silently-clamped' ($beamGenerator.Contains('input.TopContinuousQty < 2 || input.BottomContinuousQty < 2') -and $beamGenerator.Contains('int qty = input.TopContinuousQty;') -and $beamGenerator.Contains('int qty = input.BottomContinuousQty;') -and [regex]::IsMatch($beamText, '_numMainTopQty = new NumericUpDown \{[^}]*Minimum = 2') -and [regex]::IsMatch($beamText, '_numMainBotQty = new NumericUpDown \{[^}]*Minimum = 2')) 'The UI enforces the generator minimum and invalid direct requests fail instead of silently changing bar counts.'
Add-Check 'beam-side-bars-require-symmetric-pair-quantity' ($beamGenerator.Contains('input.SideBarQty < 0 || input.SideBarQty % 2 != 0') -and $beamGenerator.Contains('sidePairs = Math.Max(input.SideBarQty / 2, input.AutoSideBars ? 1 : 0)')) 'Beam side-bar counts reject negative/odd direct requests while automatic skin bars preserve their symmetric pair minimum.'
Add-Check 'beam-hanger-quantity-respects-disable-and-spacing' ($beamGenerator.Contains('input.HangerStirrupQty < 0') -and $beamGenerator.Contains('if (qty == 0) return hoops;') -and $beamGenerator.Contains('ToFeet(input.HangerStirrupSpacingMm)')) 'A zero hanger quantity disables optional hanger bars; negative counts and non-finite/non-positive enabled spacing are rejected instead of silently clamped.'
Add-Check 'beam-preview-fingerprint-covers-discovered-support-context' ($previewService.Contains('GetReinforcementContextFingerprint(input.Beam)') -and $beamGenerator.Contains('GetReinforcementContextFingerprint(FamilyInstance beam)') -and $beamGenerator.Contains('FindIntersectingSecondaryBeams(beam, intersectingBeams)') -and $beamGenerator.Contains('FindSupportingColumn(endPoint)') -and $beamGenerator.Contains('FindSupportingBeam(endPoint, beam)')) 'Beam preview invalidates when generator-discovered supports or intersecting secondary beams change.'
Add-Check 'slab-solver-preview-calls-production-generator' ($slabText.Contains('RebarPreviewService.Capture') -and $slabText.Contains('generator.GeneratePanel(panel') -and $slabText.Contains('RebarPreviewService.Matches')) 'Slab preview and pre-commit verification invoke SlabRebarGenerator.'
Add-Check 'slab-unsupported-settings-are-disclosed-and-disabled' ($slabText.Contains('Enabled = false') -and $slabText.Contains('HookDownEdge = false;') -and $slabText.Contains('TopDistribution.Enabled = false;') -and $slabText.Contains('TopHookDown = false,') -and $slabText.Contains('TopHookTailMm = 0,') -and $slabEdgeText.Contains('ReadOnly = true')) 'Unimplemented slab hook, distribution, anchor, support-type, and bottom-edge controls are disclosed/disabled instead of implying execution.'
Add-Check 'slab-opening-trim-rejects-unsupported-shapes' ($slabGenerator.Contains('TryGetAxisAlignedRectangularOpeningBounds') -and $slabGenerator.Contains('report.AddError(floor, "Opening trim geometry", unsupported)') -and $slabGenerator.Contains('Automatic opening trim bars currently support axis-aligned rectangular openings only')) 'Opening trim bars reject rotated/non-rectangular openings instead of using a misleading global bounding box.'
Add-Check 'slab-opening-trimmer-requires-full-concrete-anchorage' ($slabGenerator.Contains('panel.Boundary == null') -and $slabGenerator.Contains('CreateOpeningTrimmerBars(panel.HostFloor, trimType, panel.Boundary') -and $slabGenerator.Contains('ContainsFullInterval(boundary, openings') -and $slabGenerator.Contains('full 40d anchorage inside the concrete boundary on all four sides') -and $slabHostScenarios.Contains('SLAB_OPENING_EDGE_ANKORAGE')) 'Opening trimmers require the analyzed host boundary and full anchorage intervals in concrete; edge/adjacent-void cases have a manual host scenario.'
Add-Check 'slab-profile-fails-closed-on-unsupported-host-geometry' ($slabGeometry.Contains('one horizontal top face and one horizontal bottom face at the model bounds') -and $slabGeometry.Contains('overall host thickness to match its structural core') -and $slabGeometry.Contains('IsSupportedHorizontalLinearLoop') -and $slabGeometry.Contains('never synthesize a rectangular opening from its bounding box') -and -not $slabGeometry.Contains('ElementIntersectsElementFilter(floor)') -and $slabHostScenarios.Contains('SLAB_UNSUPPORTED_HOST_GEOMETRY')) 'Slab profile analysis rejects mismatched finish/core thickness, sloped, stepped, tapered/multi-face, and curved geometry; it consumes actual top-face loops, not synthesized opening bounding boxes; host case remains unexecuted.'
Add-Check 'beam-and-slab-canonical-solver-plans' ($beamGenerator.Contains('Generate(') -and $slabGenerator.Contains('GeneratePanel(') -and $previewService.Contains('request.Generate()')) 'Preview delegates to production generators in the rollback-only request boundary; execution uses those same generators.'
Add-Check 'all-host-stale-preview-revalidation' ($columnText.Contains('FingerprintInputs(inputGroups.SelectMany(group => group).Select(RebarPreviewService.Fingerprint))') -and $beamText.Contains('FingerprintInputs(generationInputs.Select(RebarPreviewService.Fingerprint))') -and $slabText.Contains('FingerprintInputs(selectedPanels.Select(generator.GetPanelInputFingerprint))') -and $columnText.Contains('_previewLifecycle.TryGetValid(currentFingerprint') -and $beamText.Contains('_previewLifecycle.TryGetValid(currentFingerprint') -and $slabText.Contains('_previewLifecycle.TryGetValid(currentFingerprint') -and $circularText.Contains('CurrentInputFingerprint()') -and $circularText.Contains('_previewLifecycle.TryGetValid(currentFingerprint') -and $previewService.Contains('CurrentInputFingerprint()')) 'Rectangular/circular columns, beam and slab recompute live fingerprints and require their accepted lifecycle snapshot before execution.'
Add-Check 'all-host-duplicate-bar-protection' ($columnText.Contains('HasExistingDuplicateBar') -and $circularText.Contains('HasExistingDuplicateBar') -and $beamText.Contains('HasExistingDuplicateBar') -and $slabText.Contains('HasExistingDuplicateBar')) 'All supported preview hosts reject existing bars matching the planned type and centerline signatures.'
Add-Check 'all-host-create-aborts-on-generator-errors' ($beamText.Contains('generator.Generate(input, report)') -and $beamText.Contains('report.HasErrors || !RebarPreviewService.Matches') -and $circularText.Contains('report.HasErrors || !RebarPreviewService.Matches') -and $slabText.Contains('report.HasErrors || !RebarPreviewService.Matches') -and $foundationText.Contains('report.HasErrors || !RebarPreviewService.Matches') -and $columnText.Contains('return !columnReport.HasErrors')) 'Beam, rectangular/circular column, slab, and foundation Create paths abort their transaction if a generator reports any error or accepted geometry parity fails.'
Add-Check 'all-host-preview-refresh-cancel-controls' ($columnText.Contains('BtnPreview3D_Click') -and $circularText.Contains('BtnPreview3D_Click') -and $beamText.Contains('BtnPreview_Click') -and $slabText.Contains('BtnPreviewRebar_Click') -and $previewForm.Contains('DialogResult.Cancel')) 'Each host can explicitly refresh through a new solve; cancel closes the detached preview without accepting it.'
Add-Check 'all-host-ui-inputs-shared-by-preview-and-create' ($columnText.Contains('BuildGenerationInputGroups(') -and $circularText.Contains('BuildGenerationInputGroups(') -and $beamText.Contains('CreateGenerationInput') -and $slabText.Contains('AssignSettingsToPanels(') -and $columnText.Contains('RebarPreviewService.Capture') -and $circularText.Contains('RebarPreviewService.Capture') -and $beamText.Contains('RebarPreviewService.Capture') -and $slabText.Contains('RebarPreviewService.Capture')) 'Preview and create consume the same UI-derived inputs for rectangular/circular columns, beam and assigned slab panels.'
$slabPaintBody = [regex]::Match($slabText, '(?s)private void PaintSlabPreview\(.*?(?=\r?\n        private static PointF\[\]\[\] DetachLoopViews)').Value
Add-Check 'slab-preview-paint-uses-detached-geometry' ($slabPaintBody.Contains('_detachedPanelGeometry.TryGetValue') -and $slabPaintBody.Contains('ProjectPath') -and $slabPaintBody -notmatch '\.Tessellate\(\)|UnitUtils\.') 'WinForms painting reads detached panel/path coordinates only; no Revit geometry/API calls occur in Paint.'
Add-Check 'slab-preview-retains-generator-role-identity' ($previewService.Contains('RoleSelector') -and $previewService.Contains('ReadPaths(new List<Rebar> { bar }, role)') -and $slabGenerator.Contains('RecordRoles(botX, "bottom-x"') -and $slabGenerator.Contains('RecordRoles(botY, "bottom-y"') -and $slabGenerator.Contains('RecordRoles(topX, "top-x"') -and $slabGenerator.Contains('RecordRoles(topY, "top-y"') -and $slabGenerator.Contains('"support-x"') -and $slabGenerator.Contains('"support-y"') -and $slabGenerator.Contains('"opening"') -and $slabGenerator.Contains('"spacer"') -and $slabText.Contains('role.EndsWith("-x"') -and $slabText.Contains('role.EndsWith("-y"') -and $slabText.Contains('MatchesSlabRoleFilter') -and $slabText.Contains('rolePath.Item1')) 'Slab solver paths keep production-generator role identity for layer, axis, support, opening and spacer filters through detached preview rendering; no coordinate-based role guessing is used.'
Add-Check 'slab-create-disabled-until-preview-valid' ($slabText.Contains('new RebarValidationRule(_btnCreateRebar') -and $slabText.Contains('_previewLifecycle.State == PreviewLifecycleState.Valid && _lastPreview != null') -and $slabText.Contains('MarkPreviewStale();')) 'The create-button validation guard requires an accepted preview and input changes invalidate it.'
Add-Check 'foundation-preview-calls-production-generator-in-rollback-capture' ($foundationText.Contains('RebarPreviewService.Capture') -and $foundationText.Contains('GenerateFoundation(generator, profile, _settings, roleByBarId)') -and $previewService.Contains('transaction.RollBack()') -and $foundationGenerator.Contains('Generate(FoundationProfile profile')) 'Foundation preview solves production generator output in the shared rollback-only capture boundary.'
Add-Check 'foundation-solver-preview-retains-generator-role-identity' ($foundationGenerator.Contains('RecordRoles(botXRebars, "bottom-x"') -and $foundationGenerator.Contains('RecordRoles(botYRebars, "bottom-y"') -and $foundationGenerator.Contains('RecordRoles(topXRebars, "top-x"') -and $foundationGenerator.Contains('RecordRoles(topYRebars, "top-y"') -and $foundationGenerator.Contains('RecordRoles(dowels, "dowel"') -and $foundationGenerator.Contains('RecordRoles(dowelStirrups, "dowel-stirrup"') -and $foundationGenerator.Contains('RecordRoles(uBars, "perimeter-u"') -and $foundationText.Contains('roleByBarId.TryGetValue') -and $previewForm.Contains('case "perimeter-u"')) 'Foundation solver paths preserve production-generator identity for bottom/top mats, dowels, dowel ties and perimeter U-bars.'
Add-Check 'foundation-perimeter-u-bars-are-explicitly-controllable' ($foundationText.Contains('_chkEnablePerimeterUStirrups') -and $foundationText.Contains('_cmbPerimeterStirrupDia') -and $foundationText.Contains('_numPerimeterStirrupSpacing') -and $foundationText.Contains('CaptureSettingsFromControls()') -and $foundationText.Contains('ApplySettingsToControls') -and $foundationText.Contains('PopulateCombo(_cmbPerimeterStirrupDia') -and $foundationText.Contains('Foundation.PerimeterUStirrups') -and $foundationText.Contains('Foundation.PerimeterUBarSpacingMm') -and $foundationGenerator.Contains('if (settings.EnablePerimeterUStirrups)') -and $foundationGenerator.Contains('Math.Min(profile.ThicknessFeet * 0.4, 1.2)')) 'Existing perimeter U-bars are visible, configurable, persisted, validated and fingerprinted; the solver-controlled leg rule is disclosed.'
Add-Check 'foundation-unimplemented-side-ties-fail-closed' ($foundationGenerator.Contains('if (settings.EnableSideTies)') -and $foundationGenerator.Contains('engineering detail is unresolved') -and $foundationSettings.Contains('public bool EnableSideTies { get; set; } = false;')) 'Unsupported foundation side ties default off and explicitly fail before any generated elements can be returned.'
Add-Check 'foundation-dowel-stirrup-minimum-is-explicit' ($foundationGenerator.Contains('settings.DowelStirrupQty < 2') -and $foundationGenerator.Contains('int qty = settings.DowelStirrupQty;') -and [regex]::IsMatch($foundationText, '_numDowelStirrupQty = new NumericUpDown \{[^}]*Minimum = 2')) 'Enabled dowel stirrup count is validated against the visible minimum instead of silently clamped.'
Add-Check 'foundation-input-fingerprint-covers-host-settings-and-types' ($previewService.Contains('Fingerprint(FoundationProfile profile, FoundationRebarSettings settings)') -and $previewService.Contains('FoundationRebarGenerator.FindBarType(types, label)') -and $previewService.Contains('FoundationElement.VersionGuid') -and $previewService.Contains('SerializeObject(settings')) 'Foundation input fingerprint includes host revision, bounding geometry, serialized settings and resolved bar types.'
Add-Check 'foundation-create-requires-fresh-preview-and-parity' ($foundationText.Contains('_previewLifecycle.TryGetValid(currentFingerprint') -and $foundationText.Contains('HasExistingDuplicateBar(_doc, profile.FoundationElement') -and $foundationText.Contains('RebarPreviewService.Matches(acceptedPreview') -and $foundationText.Contains('TransactionBoundary.Execute(_doc')) 'Foundation create rejects stale/missing preview and duplicates, then checks centerline parity before transaction completion.'
$foundationPaintBody = [regex]::Match($foundationText, '(?s)private void PreviewPanel_Paint\(.*?(?=\r?\n        private void AttachPreviewInvalidationHandlers)').Value
Add-Check 'foundation-2d-preview-draws-detached-solver-output' ($foundationPaintBody.Contains('_previewOutlines.TryGetValue') -and $foundationPaintBody.Contains('_lastPreview?.Find(fingerprint)') -and $foundationPaintBody.Contains('component.Paths') -and $foundationPaintBody -notmatch 'DrawLine\(pRed|new XYZ|\.get_BoundingBox\(') 'Foundation 2D view uses detached host bounds and actual solver paths; hard-coded schematic rebar was removed from Paint.'
$circularPaintBody = [regex]::Match($circularText, '(?s)private void PreviewPanel_Paint\(.*?(?=\r?\n        private void AttachPreviewInvalidationHandlers)').Value
$paintApiCallPattern = 'GetGeometry|GetRectangularProfile|GetCircularProfile|LookupParameter|_doc\.GetElement|FilteredElementCollector|UnitUtils\.|new Transaction|Regenerate\('
Add-Check 'all-rebar-paint-handlers-avoid-revit-api' ($columnPaintBody.Length -gt 0 -and $slabPaintBody.Length -gt 0 -and $foundationPaintBody.Length -gt 0 -and $circularPaintBody.Length -gt 0 -and @($columnPaintBody, $slabPaintBody, $foundationPaintBody, $circularPaintBody | Where-Object { $_ -match $paintApiCallPattern }).Count -eq 0) 'Column, circular-column, slab, and foundation Paint handlers consume detached/cached values and do not call Revit API, geometry extraction, unit conversion, or transactions.'
Add-Check 'foundation-preview-host-fixture-registered-and-truthful' ($registryText.Contains('new FoundationRebarRuntimeFixture()') -and $foundationRuntime.Contains('RebarPreviewService.Capture') -and $foundationRuntime.Contains('FR_PARITY') -and $foundationRuntime.Contains('FR_CANCEL')) 'Foundation host preview, rollback, and parity fixture is registered for host execution; static audit does not claim it ran.'
Add-Check 'circular-column-preview-calls-production-generator-in-rollback-capture' ($circularText.Contains('RebarPreviewService.Capture') -and $circularText.Contains('generator.Generate(input, report)') -and $circularText.Contains('RebarSolverPreviewForm')) 'Circular-column preview uses production generator output and detached solved centerlines.'
Add-Check 'circular-column-uniform-tie-spacing-reaches-both-zones' ($circularText.Contains('StirrupSpacingA1 = UnitUtils.ConvertToInternalUnits((double)_numStirrupSpacing.Value') -and $circularText.Contains('StirrupSpacingA2 = UnitUtils.ConvertToInternalUnits((double)_numStirrupSpacing.Value') -and $circularGenerator.Contains('Math.Max(input.ZoneA1Length, Math.Max(clearHeight / 6.0, profile.Diameter))') -and $circularText.Contains('A1') -and $circularText.Contains('600 mm') -and $circularText.Contains('grpHook.Enabled = false;') -and $circularText.Contains('grpBendCut.Enabled = false;') -and $circularText.Contains('grpTopRoof.Enabled = false;') -and $circularText.Contains('grpSplicePos.Enabled = false;') -and $circularText.Contains('grpAssignInfo.Enabled = false;') -and $circularText.Contains('grpSlabBeam.Enabled = false;')) 'Circular-column uniform stirrup spacing drives both zones, the A1 label identifies its 600 mm minimum, and unmapped general settings are visibly disabled.'
Add-Check 'circular-column-create-requires-fresh-preview-and-parity' ($circularText.Contains('_previewLifecycle.TryGetValid(currentFingerprint') -and $circularText.Contains('HasExistingDuplicateBar(_doc, input.Column') -and $circularText.Contains('RebarPreviewService.Matches(acceptedPreview') -and $circularText.Contains('CurrentInputFingerprint()')) 'Circular-column Create requires the current aggregate fingerprint, rejects duplicates and verifies solved centerline parity.'
Add-Check 'circular-column-preview-fixture-registered-and-truthful' ($registryText.Contains('new CircularColumnPreviewRuntimeFixture()') -and $circularRuntime.Contains('CC-PREVIEW_REFRESH') -and $circularRuntime.Contains('CC-PREVIEW_CANCEL') -and $circularRuntime.Contains('CC-PREVIEW_PARITY') -and $circularRuntime.Contains('CC-PREVIEW_ROLLBACK')) 'Circular-column runtime scenarios are registered/not executed; fixture checks refresh, cancellation, parity and rollback.'
Add-Check 'circular-column-no-independent-schematic-preview' ($circularText.Contains('No solved geometry displayed') -and $circularText -notmatch 'g.DrawEllipse\(penColumn' -and $circularText.Contains('PreviewPanel_Paint')) 'The former decorative bar sketch is removed; the form directs users to the production solver preview.'
Add-Check 'circular-column-visible-stale-preview-state' ($circularText.Contains('AttachPreviewInvalidationHandlers(tabControl)') -and $circularText.Contains('MarkPreviewStale();') -and $circularText.Contains('The previous preview is stale.')) 'Circular-column host selection and parameter edits mark the displayed preview stale and refresh the guarded Create state.'
Add-Check 'all-host-runtime-fixtures-registered' ($registryText.Contains('new RectangularColumnPreviewRuntimeFixture()') -and $registryText.Contains('new CircularColumnPreviewRuntimeFixture()') -and $registryText.Contains('new RectangularBeamPreviewRuntimeFixture()') -and $registryText.Contains('new RotatedBeamPreviewRuntimeFixture()') -and $registryText.Contains('new RectangularSlabPreviewRuntimeFixture()') -and $registryText.Contains('new SlabOpeningPreviewRuntimeFixture()')) $registryPath
$hostScenariosPath = Join-Path $repoRoot 'Tools\RebarPreviewHostScenarios.md'
$hostScenarios = if (Test-Path -LiteralPath $hostScenariosPath) { Get-Content -Raw $hostScenariosPath } else { '' }
Add-Check 'beam-rejects-unsupported-host-solids' ($beamGeometry.Contains('AnalyzeRectangularPrism') -and $beamGeometry.Contains('straight framing location lines only') -and $beamGeometry.Contains('six-face rectangular prism') -and $beamGeometry.Contains('cornerKeys.Count != 8') -and $beamGeometry.Contains('expectedVolume') -and $hostScenarios.Contains('BEAM_GEOMETRY_REJECTION')) 'Beam profile analysis accepts only a straight constant rectangular prism proven by physical faces, corners and volume; unsupported geometry is registered as host-only/not executed.'
Add-Check 'rectangular-column-rejects-unsupported-host-solids' ($rectangularGeometry.Contains('CollectInstanceSolids') -and $rectangularGeometry.Contains('six-face rectangular prism') -and $rectangularGeometry.Contains('cornerKeys.Count != 8') -and $rectangularGeometry.Contains('expectedVolume') -and $rectangularGeometry.Contains('column.GetTransform()') -and $hostScenarios.Contains('COLUMN_GEOMETRY_REJECTION')) 'Rectangular-column analysis proves one vertical plan-rotated rectangular prism from its physical faces, corners and volume; unsupported host geometry is registered as host-only/not executed.'
Add-Check 'circular-column-rejects-unsupported-host-solids' ($circularGeometry.Contains('GetSupportedCircularCylinder') -and $circularGeometry.Contains('OfType<CylindricalFace>()') -and $circularGeometry.Contains('one cylindrical side face and two planar end faces') -and $circularGeometry.Contains('expectedVolume') -and $circularGeometry.Contains('verticalAxis') -and $hostScenarios.Contains('CIRCULAR_COLUMN_GEOMETRY_REJECTION')) 'Circular-column profile accepts only a single vertical, constant-radius cylindrical solid with planar ends; unsupported geometry is registered as host-only/not executed.'
Add-Check 'circular-column-joint-search-is-bounded-and-fails-visible' ($circularGenerator.Contains('BoundingBoxIntersectsFilter(beamSearch)') -and $circularGenerator.Contains('Circular-column bounds are unavailable while resolving the beam-column joint zone') -and $circularGenerator -notmatch 'catch\s*\{\s*return 0;\s*\}') 'Joint-zone beam lookup uses a model-space bounding-box quick filter and does not silently convert query failures into a zero-depth joint.'
Add-Check 'column-beam-slab-foundation-host-scenarios-registered' (@('COLUMN_UNDO', 'COLUMN_GOLDEN_LAYOUT', 'COLUMN_GEOMETRY_REJECTION', 'CIRCULAR_COLUMN_UNDO', 'CIRCULAR_COLUMN_CANCEL', 'CIRCULAR_COLUMN_DUPLICATE', 'CIRCULAR_COLUMN_GEOMETRY_REJECTION', 'CIRCULAR_COLUMN_JOINT_BEAM_SEARCH', 'BEAM_UNDO', 'BEAM_GEOMETRY_REJECTION', 'BEAM_SUPPORT_STALE', 'SLAB_UNDO', 'SLAB_GOLDEN_LAYOUT', 'SLAB_OPENING_SHAPE_REJECTION', 'SLAB_OPENING_EDGE_ANKORAGE', 'SLAB_UNSUPPORTED_HOST_GEOMETRY', 'FOUNDATION_UNDO', 'FOUNDATION_CANCEL', 'FOUNDATION_DUPLICATE', 'FOUNDATION_ROTATION_REJECTION', 'FOUNDATION_SHAPE_REJECTION', 'REBAR_FACE_SPECIFIC_COVER' | Where-Object { -not $hostScenarios.Contains($_) }).Count -eq 0) 'Tools/RebarPreviewHostScenarios.md registers host-only column/slab goldens plus create/Undo/cancel/duplicate/stale-support/unsupported-geometry/cover scenarios as NOT_EXECUTED.'
Add-Check 'column-golden-host-scenario-specifies-structural-checks' ($hostScenarios.Contains('350 x 1000 mm') -and $hostScenarios.Contains('16 x 25 mm longitudinal-bar configuration') -and $hostScenarios.Contains('25 mm cover') -and $hostScenarios.Contains('compare solved preview paths and created bars')) 'The 350 x 1000 mm / 16 x 25 mm / 25 mm-cover rectangular-column golden is registered for semantic Revit host comparison and remains unexecuted.'
Add-Check 'slab-golden-host-scenario-specifies-layer-checks' ($hostScenarios.Contains('6000 x 8000 x 200 mm horizontal rectangular structural slab') -and $hostScenarios.Contains('enabled bottom/top X/Y meshes') -and $hostScenarios.Contains('PLAN and SECTION X/Y centerlines') -and $hostScenarios.Contains('structural-core and axis-aligned geometry requirements')) 'The rectangular-slab top/bottom X/Y golden is registered with explicit preview/create geometry comparisons and supported-host constraints; it remains unexecuted.'
Add-Check 'foundation-rotation-unsupported-host-fails-closed' ($foundationGeometry.Contains('HasAxisAlignedPlanBasis(foundation.GetTransform())') -and $foundationGeometry.Contains('Foundation reinforcement currently supports axis-aligned plan hosts only') -and $hostScenarios.Contains('FOUNDATION_ROTATION_REJECTION')) 'Foundation bounding-box generation rejects rotated plan hosts before solver capture and records a manual host scenario.'
Add-Check 'foundation-nonrectangular-hosts-fail-closed' ($foundationGeometry.Contains('HasSingleAxisAlignedRectangularSolid(foundation, bb)') -and $foundationGeometry.Contains('CollectInstanceSolids(foundation.get_Geometry(options), solids)') -and $foundationGeometry.Contains('candidate.Faces') -and $hostScenarios.Contains('FOUNDATION_SHAPE_REJECTION')) 'Foundation profile analysis rejects non-planar, tapered, stepped, multi-solid, or non-box hosts before preview capture and records a manual host scenario.'

$wallCommand = Get-ChildItem -LiteralPath (Join-Path $base 'Commands') -File -Filter '*Wall*Rebar*.cs'
$wallGenerator = Get-ChildItem -LiteralPath (Join-Path $base 'Core') -File -Filter '*Wall*Rebar*.cs'
Add-Check 'wall-rebar-explicitly-unsupported' ($wallCommand.Count -eq 0 -and $wallGenerator.Count -eq 0) 'No wall command/generator; documentation must retain this boundary.'

$columnDrawingPath = Join-Path $base 'Commands\CmdColumnDrawing.cs'
$columnDrawing = Get-Content -Raw $columnDrawingPath
Add-Check 'column-drawing-checked-transaction-ownership' ($columnDrawing.Contains('TransactionBoundary.ExecuteGroup') -and $columnDrawing.Contains('TransactionBoundary.Execute(doc') -and $columnDrawing -notmatch 'new Transaction\(|tx\.Start\(\)|tx\.Commit\(\)') $columnDrawingPath
Add-Check 'column-drawing-three-view-postconditions' ($columnDrawing.Contains('ViewDrafting drawingView') -and $columnDrawing.Contains('ViewPlan sectionView') -and $columnDrawing.Contains('View3D inspectionView') -and $columnDrawing.Contains('generatedViewIds.Any') -and $columnDrawing.Contains('doc.GetElement(id)')) 'Drafting, section, and 3D views are checked before transaction-group assimilation.'

$passCount = @($checks | Where-Object Pass).Count
$failures = @($checks | Where-Object { -not $_.Pass })
foreach ($check in $checks) {
    $status = if ($check.Pass) { 'PASS' } else { 'BLOCKED' }
    Write-Output ("{0} {1} - {2}" -f $status, $check.Name, $check.Evidence)
}
Write-Output ("KREBAR_STATIC_CHECKS={0}/{1}" -f $passCount, $checks.Count)
if ($failures.Count -gt 0) {
    Write-Output 'KREBAR_PREVIEW_ACCEPTANCE=BLOCKED'
    Write-Output 'KREBAR_STATIC_ACCEPTANCE=PARTIAL'
    exit 1
}

Write-Output 'KREBAR_STATIC_ACCEPTANCE=PASS'
exit 0
