$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$featureRoot = Join-Path $root 'KhimTools\Tools\KhimGen\ModifyObjects'
$checks = 0
function Read-Feature([string]$relative) { $path = Join-Path $featureRoot $relative; if (-not (Test-Path -LiteralPath $path)) { throw "FAIL: missing Modify Objects file $relative" }; return Get-Content -LiteralPath $path -Raw }
function Read-Repo([string]$relative) { $path = Join-Path $root $relative; if (-not (Test-Path -LiteralPath $path)) { throw "FAIL: missing repository file $relative" }; return Get-Content -LiteralPath $path -Raw }
function Assert-Text([string]$text, [string]$needle, [string]$label) { if ($text.IndexOf($needle, [StringComparison]::Ordinal) -lt 0) { throw "FAIL: $label" }; $script:checks++ }
function Assert-NotText([string]$text, [string]$needle, [string]$label) { if ($text.IndexOf($needle, [StringComparison]::Ordinal) -ge 0) { throw "FAIL: $label" }; $script:checks++ }
$core = (Get-ChildItem (Join-Path $featureRoot 'Core') -Filter '*.cs' -Recurse | ForEach-Object { Get-Content $_.FullName -Raw }) -join "`n"
$services = (Get-ChildItem (Join-Path $featureRoot '*') -Filter '*.cs' -Recurse | ForEach-Object { Get-Content $_.FullName -Raw }) -join "`n"
$command = Read-Feature 'Commands\CmdModifyObjects.cs'; $form = Read-Feature 'Forms\ModifyObjectsForm.cs'
foreach ($file in @('Core\ModifyObjectContext.cs','Core\ModifyObjectPlan.cs','Core\ModifyObjectPreflight.cs','Core\ModifyObjectResult.cs','Core\ModifyObjectStatus.cs','Structural\ColumnSplitService.cs','Structural\ColumnJoinService.cs','Structural\BeamSplitService.cs','Structural\BeamJoinService.cs','Structural\SlabJoinAdapter.cs','Structural\SlabSplitService.cs','Wall\WallSplitService.cs','Wall\WallTrimService.cs','Wall\WallOpeningService.cs','General\Move3DService.cs','General\Array3DService.cs','General\PartsService.cs','General\ColumnBaseElevationService.cs')) { Assert-Text $services ([IO.Path]::GetFileNameWithoutExtension($file)) "architecture $file" }
Assert-Text $command 'class CmdModifyObjects : IExternalCommand' 'public command'; Assert-Text $command 'Transaction(TransactionMode.Manual)' 'manual transaction'; Assert-Text $command 'Preview' 'preview boundary'; Assert-Text $command 'Preflight' 'preflight boundary'; Assert-Text $command 'ExecutePlan' 'thin command dispatcher'; Assert-Text $form 'Modify Objects 2.0' 'form title'; Assert-Text $form 'STRUCTURE' 'structure tab'; Assert-Text $form 'WALL' 'wall tab'; Assert-Text $form 'GENERAL' 'general tab'; Assert-Text $form 'Preview' 'preview action'; Assert-Text $form 'Apply' 'apply action'; Assert-Text $form 'Cancel' 'cancel action'; Assert-Text $form 'TableLayoutPanel' 'responsive layout'; Assert-Text $form 'MinimumSize' 'DPI-safe form'; Assert-Text $form 'No model writes occurred' 'preview write boundary'
foreach ($token in @('SELECT','ANALYZE','PLAN','PREFLIGHT','EXECUTE','REGENERATE','VERIFY','RESULT','ModifyObjectPlanBuilder','ModifyObjectPreflight','TransactionGroup','Transaction','SubTransaction','POST_VERIFY_FAILED','STALE_PLAN','GROUP_CONSTRAINED','PINNED','DESIGN_OPTION_BLOCKED','WORKSHARING_BLOCKED','HOST_DEPENDENCY_RISK','PARAMETER_CONFLICT','HOSTED_CONTENT_RISK','OPENING_CONFLICT','COPY_UNSUPPORTED','COLUMN_GEOMETRY_UNSUPPORTED','ATTACHED_COLUMN_UNSUPPORTED','BEAM_GEOMETRY_UNSUPPORTED','OPENING_CROSSES_SPLIT','SHAPE_EDITED_FLOOR_UNSUPPORTED','SLAB_SPLIT_CAPABILITY_UNSUPPORTED','NO_INTERSECTION','ALREADY_JOINED','NOT_JOINED','DELETED_SOURCE','PARTIAL','NO_CHANGE')) { Assert-Text $services $token "status/pipeline token $token" }
foreach ($token in @('COLUMN_SPLIT','COLUMN_JOIN','BEAM_SPLIT','BEAM_JOIN','SLAB_SPLIT','SLAB_JOIN','WALL_SPLIT','WALL_TRIM','WALL_OPENING','MOVE_3D','ARRAY_3D','CREATE_PARTS','COLUMN_BASE_ELEVATION')) { Assert-Text $core $token "operation $token" }
Assert-Text $services 'JoinGeometryUtils' 'existing join API is reused by adapter'; Assert-Text $services 'SlabJoinService' 'existing slab service is reused'; Assert-Text $services 'WallUtils' 'wall join endpoint handling'; Assert-Text $services 'Wall.Create' 'wall split creation'; Assert-Text $services 'NewOpening' 'actual wall opening API'; Assert-Text $services 'PartUtils.AreElementsValidForCreateParts' 'Parts capability preflight'; Assert-Text $services 'PartUtils.CreateParts' 'Parts execution'; Assert-Text $services 'ElementTransformUtils.MoveElements' 'MoveElements API'; Assert-Text $services 'ElementTransformUtils.CopyElement' 'deterministic array copy'; Assert-Text $services 'UnitUtils.ConvertToInternalUnits' 'unit-aware move'; Assert-Text $services 'UnitTypeId.Millimeters' 'millimeter unit'; Assert-Text $services 'FAMILY_BASE_LEVEL_PARAM' 'base level'; Assert-Text $services 'FAMILY_BASE_LEVEL_OFFSET_PARAM' 'base offset'; Assert-Text $services 'FAMILY_TOP_LEVEL_PARAM' 'top constraint preservation'; Assert-Text $services 'ParameterTransferService.CreateKey' 'safe parameter identity reuse'; Assert-Text $services 'ParameterTransferService.TryApplyValue' 'typed parameter transfer'; Assert-Text $services 'IsReadOnly' 'read-only preflight'; Assert-Text $services 'LocationCurve' 'curve geometry audit'; Assert-Text $services 'LocationPoint' 'column point geometry audit'; Assert-Text $services 'StructuralType.Column' 'column family creation'; Assert-Text $services 'StructuralType.Beam' 'beam family creation'; Assert-Text $services 'CopyElement' 'copy operation'; Assert-Text $services 'IncludeOriginal' 'array original policy'; Assert-Text $services 'IsStale' 'stale plan guard'; Assert-Text $services 'Regenerate' 'post operation regeneration'; Assert-Text $services 'VerificationPassed' 'post verify result'; Assert-Text $services 'TryCopySafeParameters' 'parameter conflict policy'
$registry = Read-Repo 'KhimTools\Tools\KhimGen\RuntimeQa\Core\RuntimeQaRegistry.cs'; $fixture = Read-Repo 'KhimTools\Tools\KhimGen\RuntimeQa\Fixtures\ModifyObjectsRuntimeFixture.cs'; $ribbon = Read-Repo 'KhimTools\Core\RibbonBuilder.cs'; Assert-Text $registry 'ModifyObjectsRuntimeFixture' 'runtime fixture registry'; Assert-Text $fixture 'MODIFY_OBJECTS_STAGE36' 'runtime fixture id'; Assert-Text $fixture 'TransactionGroup rollback' 'runtime rollback boundary'; Assert-Text $fixture 'Block(' 'blocked prerequisite policy'; Assert-Text $ribbon 'KhimTools.ModifyObjects.Commands.CmdModifyObjects' 'ribbon command registration'
foreach ($file in (Get-ChildItem -LiteralPath $featureRoot -Recurse -Filter '*.cs')) { $text = Get-Content -LiteralPath $file.FullName -Raw; if ($text -match '(?ms)catch\s*\{\s*\}') { throw "FAIL: silent catch in $($file.FullName)" }; $checks++ }
Assert-NotText $services 'Floor.Split(' 'no invented Floor.Split API'; Assert-NotText $services 'SwallowWarningsPreprocessor' 'new module does not swallow warnings'; Assert-NotText $services 'catch { }' 'no silent catches'
Write-Output "PASS: $checks Modify Objects Stage 3.6 static checks. No Revit model operation executed."
